export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';

export const NOTIFICATION_DATA_LOADING = 'NOTIFICATION_DATA_LOADING';
export const NOTIFICATION_DATA_SUCCESS = 'NOTIFICATION_DATA_SUCCESS';
export const NOTIFICATION_DATA_FAILURE = 'NOTIFICATION_DATA_FAILURE';

// home details api 
export const GET_HOME_DETAILS_LOADING = 'GET_HOME_DETAILS_LOADING';
export const GET_HOME_DETAILS_SUCCESS = 'GET_HOME_DETAILS_SUCCESS';
export const GET_HOME_DETAILS_FAILURE = 'GET_HOME_DETAILS_FAILURE';

// list model
export const GET_MODEL_LIST_LOADING = 'GET_MODEL_LIST_LOADING';
export const GET_MODEL_LIST_SUCCESS = 'GET_MODEL_LIST_SUCCESS';
export const GET_MODEL_LIST_FAILURE = 'GET_MODEL_LIST_FAILURE';

// product details
export const GET_PRODUCT_DETAILS_LOADING = 'GET_PRODUCT_DETAILS_LOADING';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE';


// add to cart 
export const Add_CART_DETAILS_LOADING = 'Add_CART_DETAILS_LOADING';
export const Add_CART_DETAILS_SUCCESS = 'Add_CART_DETAILS_SUCCESS';
export const Add_CART_DETAILS_FAILURE = 'Add_CART_DETAILS_FAILURE';

// list to cart 
export const GET_MYCART_DETAILS_LOADING = 'GET_MYCART_DETAILS_LOADING';
export const GET_MYCART_DETAILS_SUCCESS = 'GET_MYCART_DETAILS_SUCCESS';
export const GET_MYCART_DETAILS_FAILURE = 'GET_MYCART_DETAILS_FAILURE';


// list to cart 
export const UPDATE_CART_QTY_LOADING = 'UPDATE_CART_QTY_LOADING';
export const UPDATE_CART_QTY_SUCCESS = 'UPDATE_CART_QTY_SUCCESS';
export const UPDATE_CART_QTY_FAILURE = 'UPDATE_CART_QTY_FAILURE';

// DELETE CART 
export const DELETE_CART_LOADING = 'DELETE_CART_LOADING';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILURE = 'DELETE_CART_FAILURE';


// order generate 

export const ORDER_GENERATE_LOADING = 'ORDER_GENERATE_LOADING';
export const ORDER_GENERATE_SUCCESS = 'ORDER_GENERATE_SUCCESS';
export const ORDER_GENERATE_FAILURE = 'ORDER_GENERATE_FAILURE';


// get order list 

export const GET_ORDER_LIST_LOADING = 'GET_ORDER_LIST_LOADING';
export const GET_ORDER_LIST_SUCCESS = 'GET_ORDER_LIST_SUCCESS';
export const GET_ORDER_LIST_FAILURE = 'GET_ORDER_LIST_FAILURE';

// get global search 

export const GET_GLOBAL_SEARCH_LOADING = 'GET_GLOBAL_SEARCH_LOADING';
export const GET_GLOBAL_SEARCH_SUCCESS = 'GET_GLOBAL_SEARCH_SUCCESS';
export const GET_GLOBAL_SEARCH_FAILURE = 'GET_GLOBAL_SEARCH_FAILURE';

// get profile details
export const GET_PROFILE_DETAILS_LOADING = 'GET_PROFILE_DETAILS_LOADING';
export const GET_PROFILE_DETAILS_SUCCESS = 'GET_PROFILE_DETAILS_SUCCESS';
export const GET_PROFILE_DETAILS_FAILURE = 'GET_PROFILE_DETAILS_FAILURE';

// get Order history
export const GET_ORDER_HISTORY_LOADING = 'GET_ORDER_HISTORY_LOADING';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE';


// get Route List 
export const GET_ROUTE_DETAILS_LOADING = 'GET_ROUTE_DETAILS_LOADING';
export const GET_ROUTE_DETAILS_SUCCESS = 'GET_ROUTE_DETAILS_SUCCESS';
export const GET_ROUTE_DETAILS_FAILURE = 'GET_ROUTE_DETAILS_FAILURE';

// get default address

export const GET_DEFAULT_ADDRESS_LOADING = 'GET_DEFAULT_ADDRESS_LOADING';
export const GET_DEFAULT_ADDRESS_SUCCESS = 'GET_DEFAULT_ADDRESS_SUCCESS';
export const GET_DEFAULT_ADDRESS_FAILURE = 'GET_DEFAULT_ADDRESS_FAILURE';

// add or update address

export const ADD_ADDRESS_LOADING = 'ADD_ADDRESS_LOADING';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';


// EDIT PROFILE

export const EDIT_PROFILE_LOADING = 'EDIT_PROFILE_LOADING';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// GET WISHLIST DATA
export const GET_WISHLIST_LOADING = 'GET_WISHLIST_LOADING';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';


// delete wishlist
export const DELETE_WISHLIST_LOADING = 'DELETE_WISHLIST_LOADING';
export const DELETE_WISHLIST_SUCCESS = 'DELETE_WISHLIST_SUCCESS';
export const DELETE_WISHLIST_FAILURE = 'DELETE_WISHLIST_FAILURE';

// add wishlist

export const ADD_WISHLIST_LOADING = 'ADD_WISHLIST_LOADING';
export const ADD_WISHLIST_SUCCESS = 'ADD_WISHLIST_SUCCESS';
export const ADD_WISHLIST_FAILURE = 'ADD_WISHLIST_FAILURE';

// list brand


export const GET_BRAND_DETAILS_LOADING = 'GET_BRAND_DETAILS_LOADING';
export const GET_BRAND_DETAILS_SUCCESS = 'GET_BRAND_DETAILS_SUCCESS';
export const GET_BRAND_DETAILS_FAILURE = 'GET_BRAND_DETAILS_FAILURE';


// list store

export const GET_STORE_LIST_LOADING = 'GET_STORE_LIST_LOADING';
export const GET_STORE_LIST_SUCCESS = 'GET_STORE_LIST_SUCCESS';
export const GET_STORE_LIST_FAILURE = 'GET_STORE_LIST_FAILURE';


// add store data
export const ADD_STORE_DATA_LOADING = 'ADD_STORE_DATA_LOADING';
export const ADD_STORE_DATA_SUCCESS = 'ADD_STORE_DATA_SUCCESS';
export const ADD_STORE_DATA_FAILURE = 'ADD_STORE_DATA_FAILURE';



export const NOTIFICATION_UPDATE_LOADING = 'NOTIFICATION_UPDATE_LOADING';
export const NOTIFICATION_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_SUCCESS';
export const NOTIFICATION_UPDATE_FAILURE = 'NOTIFICATION_UPDATE_FAILURE';

export const NOTIFICATION_INSERT_LOADING = 'NOTIFICATION_INSERT_LOADING';
export const NOTIFICATION_INSERT_SUCCESS = 'NOTIFICATION_INSERT_SUCCESS';
export const NOTIFICATION_INSERT_FAILURE = 'NOTIFICATION_INSERT_FAILURE';

export const DELETE_BANK_LOADING = 'DELETE_BANK_LOADING';
export const DELETE_BANK_SUCCESS = 'DELETE_BANK_SUCCESS';
export const DELETE_BANK_FAILURE = 'DELETE_BANK_FAILURE';

export const DELETE_CREDITCARD_LOADING = 'DELETE_CREDITCARD_LOADING';
export const DELETE_CREDITCARD_SUCCESS = 'DELETE_CREDITCARD_SUCCESS';
export const DELETE_CREDITCARD_FAILURE = 'DELETE_CREDITCARD_FAILURE';

export const BANK_DATA_LOADING = 'BANK_DATA_LOADING';
export const BANK_DATA_SUCCESS = 'BANK_DATA_SUCCESS';
export const BANK_DATA_FAILURE = 'BANK_DATA_FAILURE';

export const NEW_BANK_LOADING = 'NEW_BANK_LOADING';
export const NEW_BANK_SUCCESS = 'NEW_BANK_SUCCESS';
export const NEW_BANK_FAILURE = 'NEW_BANK_FAILURE';

export const BANK_LOADING = 'BANK_LOADING';
export const BANK_SUCCESS = 'BANK_SUCCESS';
export const BANK_FAILURE = 'BANK_FAILURE';

export const GET_REFCODE_LOADING = 'GET_REFCODE_LOADING';
export const GET_REFCODE_SUCCESS = 'GET_REFCODE_SUCCESS';
export const GET_REFCODE_FAILURE = 'GET_REFCODE_FAILURE';

export const NEW_CREDITCARD_LOADING = 'NEW_CREDITCARD_LOADING';
export const NEW_CREDITCARD_SUCCESS = 'NEW_CREDITCARD_SUCCESS';
export const NEW_CREDITCARD_FAILURE = 'NEW_CREDITCARD_FAILURE';

export const CREDITCARD_DATA_LOADING = 'CREDITCARD_DATA_LOADING';
export const CREDITCARD_DATA_SUCCESS = 'CREDITCARD_DATA_SUCCESS';
export const CREDITCARD_DATA_FAILURE = 'CREDITCARD_DATA_FAILURE';

export const CREDITCARD_LOADING = 'CREDITCARD_LOADING';
export const CREDITCARD_SUCCESS = 'CREDITCARD_SUCCESS';
export const CREDITCARD_FAILURE = 'CREDITCARD_FAILURE';

export const USER_DATA_LOADING = 'USER_DATA_LOADING';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

// Budget

export const FAVOURITE_STORE_LOADING = 'FAVOURITE_STORE_LOADING';
export const FAVOURITE_STORE_SUCCESS = 'FAVOURITE_STORE_SUCCESS';
export const FAVOURITE_STORE_FAILURE = 'FAVOURITE_STORE_FAILURE';

// Transaction filter
export const DATE_FILTER_LOADING = 'DATE_FILTER_LOADING';
export const DATE_FILTER_SUCCESS = 'DATE_FILTER_SUCCESS';
export const DATE_FILTER_FAILURE = 'DATE_FILTER_FAILURE';

// Otp constants after registeration
export const OTP_LOADING = 'OTP_LOADING';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILURE = 'OTP_FAILURE';

// To verify otp after registration
export const VERIFY_OTP_LOADING = 'VERIFY_OTP_LOADING';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// For forgot password
export const FORGOTPASSWORD_LOADING = 'FORGOTPASSWORD_LOADING';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAILURE = 'FORGOTPASSWORD_FAILURE';

// For change password
export const CHANGEPASSWORD_LOADING = 'CHANGEPASSWORD_LOADING';
export const CHANGEPASSWORD_SUCCESS = 'CHANGEPASSWORD_SUCCESS';
export const CHANGEPASSWORD_FAILURE = 'CHANGEPASSWORD_FAILURE';
// To verify otp after registration
export const SOCIAL_LOGIN_LOADING = 'SOCIAL_LOGIN_LOADING';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';

// To update contact while sociallogin
export const UPDATE_CONTACT_LOADING = 'UPDATE_CONTACT_LOADING';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE';

// To upload prof image
export const UPLOAD_PROFILE_IMAGE_LOADING = 'UPLOAD_PROFILE_IMAGE_LOADING';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAILURE = 'UPLOAD_PROFILE_IMAGE_FAILURE';

export const ABOUT_ME_LOADING = 'ABOUT_ME_LOADING';
export const ABOUT_ME_SUCCESS = 'ABOUT_ME_SUCCESS';
export const ABOUT_ME_FAILURE = 'ABOUT_ME_FAILURE';

export const SMSRETRIVE_LOADING = 'SMSRETRIVE_LOADING';
export const SMSRETRIVE_SUCCESS = 'SMSRETRIVE_SUCCESS';
export const SMSRETRIVE_FAILURE = 'SMSRETRIVE_FAILURE';

export const GET_EXPENSES_LOADING = 'GET_EXPENSES_LOADING';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE';

export const GET_GETMAXDATE_LOADING = 'GET_GETMAXDATE_LOADING';
export const GET_GETMAXDATE_SUCCESS = 'GET_GETMAXDATE_SUCCESS';
export const GET_GETMAXDATE_FAILURE = 'GET_GETMAXDATE_FAILURE';

// To delete transaction list
export const DELETE_TRANSACTION_LOADING = 'DELETE_TRANSACTION_LOADING';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

export const PERSONAL_TRANSACTION_LOADING = 'PERSONAL_TRANSACTION_LOADING';
export const PERSONAL_TRANSACTION_SUCCESS = 'PERSONAL_TRANSACTION_SUCCESS';
export const PERSONAL_TRANSACTION_FAILURE = 'PERSONAL_TRANSACTION_FAILURE';

// To get income types
export const GET_INCOMETYPES_LOADING = 'GET_INCOMETYPES_LOADING';
export const GET_INCOMETYPES_SUCCESS = 'GET_INCOMETYPES_SUCCESS';
export const GET_INCOMETYPES_FAILURE = 'GET_INCOMETYPES_FAILURE';

// To edit income data
export const EDIT_INCOME_LOADING = 'EDIT_INCOME_LOADING';
export const EDIT_INCOME_SUCCESS = 'EDIT_INCOME_SUCCESS';
export const EDIT_INCOME_FAILURE = 'EDIT_INCOME_FAILURE';

// To add incomes data
export const ADD_INCOME_LOADING = 'ADD_INCOME_LOADING';
export const ADD_INCOME_SUCCESS = 'ADD_INCOME_SUCCESS';
export const ADD_INCOME_FAILURE = 'ADD_INCOME_FAILURE';

// Get goal categories
export const GET_GOALCATEGORIES_LOADING = 'GET_GOALCATEGORIES_LOADING';
export const GET_GOALCATEGORIES_SUCCESS = 'GET_GOALCATEGORIES_SUCCESS';
export const GET_GOALCATEGORIES_FAILURE = 'GET_GOALCATEGORIES_FAILURE';

// Submit financial goal
export const SET_FINANCIALGOAL_LOADING = 'SET_FINANCIALGOAL_LOADING';
export const SET_FINANCIALGOAL_SUCCESS = 'SET_FINANCIALGOAL_SUCCESS';
export const SET_FINANCIALGOAL_FAILURE = 'SET_FINANCIALGOAL_FAILURE';

// Set achieve goal
export const SET_ACHIEVEGOAL_LOADING = 'SET_ACHIEVEGOAL_LOADING';
export const SET_ACHIEVEGOAL_SUCCESS = 'SET_ACHIEVEGOAL_SUCCESS';
export const SET_ACHIEVEGOAL_FAILURE = 'SET_ACHIEVEGOAL_SUCCESS';

// To get all financial goals
export const GET_FINANCIALGOALS_LOADING = 'GET_FINANCIALGOALS_LOADING';
export const GET_FINANCIALGOALS_SUCCESS = 'GET_FINANCIALGOALS_SUCCESS';
export const GET_FINANCIALGOALS_FAILURE = 'GET_FINANCIALGOALS_FAILURE';

// To get the financial entered goals
export const GET_FINANCEDATA_LOADING = 'GET_FINANCEDATA_LOADING';
export const GET_FINANCEDATA_SUCCESS = 'GET_FINANCEDATA_SUCCESS';
export const GET_FINANCEDATA_FAILURE = 'GET_FINANCEDATA_FAILURE';

// Set monthly investment
export const SET_MONTHLY_INVESTMENT_LOADING = 'SET_MONTHLY_INVESTMENT_LOADING';
export const SET_MONTHLY_INVESTMENT_SUCCESS = 'SET_MONTHLY_INVESTMENT_SUCCESS';
export const SET_MONTHLY_INVESTMENT_FAILURE = 'SET_MONTHLY_INVESTMENT_FAILURE';

// To get credit card data from sms
export const CREDITCARD_RETRIVE_LOADING = 'CREDITCARD_RETRIVE_LOADING';
export const CREDITCARD_RETRIVE_SUCCESS = 'CREDITCARD_RETRIVE_SUCCESS';
export const CREDITCARD_RETRIVE_FAILURE = 'CREDITCARD_RETRIVE_FAILURE';

// To get due data from sms
export const DUE_TRANSACTION_LOADING = 'DUE_TRANSACTION_LOADING';
export const DUE_TRANSACTION_SUCCESS = 'DUE_TRANSACTION_SUCCESS';
export const DUE_TRANSACTION_FAILURE = 'DUE_TRANSACTION_FAILURE';

// Delete or archieve the goal
export const UPDATE_GOAL_STATUS_LOADING = 'UPDATE_GOAL_STATUS_LOADING';
export const UPDATE_GOAL_STATUS_SUCCESS = 'UPDATE_GOAL_STATUS_SUCCESS';
export const UPDATE_GOAL_STATUS_FAILURE = 'UPDATE_GOAL_STATUS_FAILURE';

// For credit card transaction
export const GET_CREDIT_TRANSACTION_LOADING = 'GET_CREDIT_TRANSACTION_LOADING';
export const GET_CREDIT_TRANSACTION_SUCCESS = 'GET_CREDIT_TRANSACTION_SUCCESS';
export const GET_CREDIT_TRANSACTION_FAILURE = 'GET_CREDIT_TRANSACTION_FAILURE';

// Set card reminder
export const CARDREMINDER_INSERT_LOADING = 'CARDREMINDER_INSERT_LOADING';
export const CARDREMINDER_INSERT_SUCCESS = 'CARDREMINDER_INSERT_SUCCESS';
export const CARDREMINDER_INSERT_FAILURE = 'CARDREMINDER_INSERT_FAILURE';

export const CARDREMINDER_DATA_LOADING = 'CARDREMINDER_DATA_LOADING';
export const CARDREMINDER_DATA_SUCCESS = 'CARDREMINDER_DATA_SUCCESS';
export const CARDREMINDER_DATA_FAILURE = 'CARDREMINDER_DATA_FAILURE';

// Kyc submit
export const SUBMITKYC_INSERT_LOADING = 'SUBMITKYC_INSERT_LOADING';
export const SUBMITKYC_INSERT_SUCCESS = 'SUBMITKYC_INSERT_SUCCESS';
export const SUBMITKYC_INSERT_FAILURE = 'SUBMITKYC_INSERT_FAILURE';

// Get kyc
export const GETKYC_DATA_LOADING = 'GETKYC_DATA_LOADING';
export const GETKYC_DATA_SUCCESS = 'GETKYC_DATA_SUCCESS';
export const GETKYC_DATA_FAILURE = 'GETKYC_DATA_FAILURE';

// Delete kyc
export const DELETE_KYC_LOADING = 'DELETE_KYC_LOADING';
export const DELETE_KYC_SUCCESS = 'DELETE_KYC_SUCCESS';
export const DELETE_KYC_FAILURE = 'DELETE_KYC_FAILURE';

// Constants for state list
export const STATE_LIST_LOADING = 'STATE_LIST_LOADING';
export const STATE_LIST_SUCCESS = 'STATE_LIST_SUCCESS';
export const STATE_LIST_FAILURE = 'STATE_LIST_FAILURE';

// Constants for support submit
export const SUPPORT_INSERT_LOADING = 'SUPPORT_INSERT_LOADING';
export const SUPPORT_INSERT_SUCCESS = 'SUPPORT_INSERT_SUCCESS';
export const SUPPORT_INSERT_FAILURE = 'SUPPORT_INSERT_FAILURE';

// Constants for feedback submit
export const FEEDBACK_INSERT_LOADING = 'FEEDBACK_INSERT_LOADING';
export const FEEDBACK_INSERT_SUCCESS = 'FEEDBACK_INSERT_SUCCESS';
export const FEEDBACK_INSERT_FAILURE = 'FEEDBACK_INSERT_FAILURE';

// Constants for rewards points
export const REWARDS_POINTS_LOADING = 'REWARDS_POINTS_LOADING';
export const REWARDS_POINTS_SUCCESS = 'REWARDS_POINTS_SUCCESS';
export const REWARDS_POINTS_FAILURE = 'REWARDS_POINTS_FAILURE';

// Constants for rewards points
export const REWARDS_HISTORY_LOADING = 'REWARDS_HISTORY_LOADING';
export const REWARDS_HISTORY_SUCCESS = 'REWARDS_HISTORY_SUCCESS';
export const REWARDS_HISTORY_FAILURE = 'REWARDS_HISTORY_FAILURE';

// Sum of floats
export const SUM_OF_FLOATS_LOADING = 'SUM_OF_FLOATS_LOADING';
export const SUM_OF_FLOATS_SUCCESS = 'SUM_OF_FLOATS_SUCCESS';
export const SUM_OF_FLOATS_FAILURE = 'SUM_OF_FLOATS_FAILURE';

// Sum of floats
export const GET_USER_FEEDBACK_LOADING = 'GET_USER_FEEDBACK_LOADING';
export const GET_USER_FEEDBACK_SUCCESS = 'GET_USER_FEEDBACK_SUCCESS';
export const GET_USER_FEEDBACK_FAILURE = 'GET_USER_FEEDBACK_FAILURE';

// Update device ID constants
export const UPDATE_DEVICEID_LOADING = 'UPDATE_DEVICEID_LOADING';
export const UPDATE_DEVICEID_SUCCESS = 'UPDATE_DEVICEID_SUCCESS';
export const UPDATE_DEVICEID_FAILURE = 'UPDATE_DEVICEID_FAILURE';

// Get MutualFund Token
export const GET_MF_TOKEN_LOADING = 'GET_MF_TOKEN_LOADING';
export const GET_MF_TOKEN_SUCCESS = 'GET_MF_TOKEN_SUCCESS';
export const GET_MF_TOKEN_FAILURE = 'GET_MF_TOKEN_FAILURE';

// Add MutualFund Investor KYC Request
export const ADD_MF_INVESTOR_KYC_LOADING = 'ADD_MF_INVESTOR_KYC_LOADING';
export const ADD_MF_INVESTOR_KYC_SUCCESS = 'ADD_MF_INVESTOR_KYC_SUCCESS';
export const ADD_MF_INVESTOR_KYC_FAILURE = 'ADD_MF_INVESTOR_KYC_FAILURE';

//  Pan Validate Request
export const CHECK_PAN_DETAILS_LOADING = 'CHECK_PAN_DETAILS_LOADING';
export const CHECK_PAN_DETAILS_SUCCESS = 'CHECK_PAN_DETAILS_SUCCESS';
export const CHECK_PAN_DETAILS_FAILURE = 'CHECK_PAN_DETAILS_FAILURE';

// Update MutualFund Investor KYC Request
export const UPDATE_MF_INVESTOR_KYC_LOADING = 'UPDATE_MF_INVESTOR_KYC_LOADING';
export const UPDATE_MF_INVESTOR_KYC_SUCCESS = 'UPDATE_MF_INVESTOR_KYC_SUCCESS';
export const UPDATE_MF_INVESTOR_KYC_FAILURE = 'UPDATE_MF_INVESTOR_KYC_FAILURE';

// Add MutualFund Investor API
export const ADD_INVESTOR_KYC_LOADING = 'ADD_INVESTOR_KYC_LOADING';
export const ADD_INVESTOR_KYC_SUCCESS = 'ADD_INVESTOR_KYC_SUCCESS';
export const ADD_INVESTOR_KYC_FAILURE = 'ADD_INVESTOR_KYC_FAILURE';

// ADD Investor Details API
export const ADD_KYC_DB_LOADING = 'ADD_KYC_DB_LOADING';
export const ADD_KYC_DB_SUCCESS = 'ADD_KYC_DB_SUCCESS';
export const ADD_KYC_DB_FAILURE = 'ADD_KYC_DB_FAILURE';

// Update Investor Details API
export const UPDATE_KYC_DB_LOADING = 'UPDATE_KYC_DB_LOADING';
export const UPDATE_KYC_DB_SUCCESS = 'UPDATE_KYC_DB_SUCCESS';
export const UPDATE_KYC_DB_FAILURE = 'UPDATE_KYC_DB_FAILURE';

// Add MutualFund Investor KYC Documents API
export const ADD_KYC_DOCUMENTS_LOADING = 'ADD_KYC_DOCUMENTS_LOADING';
export const ADD_KYC_DOCUMENTS_SUCCESS = 'ADD_KYC_DOCUMENTS_SUCCESS';
export const ADD_KYC_DOCUMENTS_FAILURE = 'ADD_KYC_DOCUMENTS_FAILURE';

// Check Pan Card Status
export const CHECK_MF_INVESTOR_PAN_LOADING = 'CHECK_MF_INVESTOR_PAN_LOADING';
export const CHECK_MF_INVESTOR_PAN_SUCCESS = 'CHECK_MF_INVESTOR_PAN_SUCCESS';
export const CHECK_MF_INVESTOR_PAN_FAILURE = 'CHECK_MF_INVESTOR_PAN_FAILURE';

// Set MutualFund Investor Details
export const SET_MF_INVESTOR_DETAILS = 'SET_MF_INVESTOR_DETAILS';
export const SET_MF_KYC_DETAILS = 'SET_MF_KYC_DETAILS';

// To fetch all purchase orders.
export const LIST_MF_PURCHASE_ORDERS_LOADING =
  'LIST_MF_PURCHASE_ORDERS_LOADING';
export const LIST_MF_PURCHASE_ORDERS_SUCCESS =
  'LIST_MF_PURCHASE_ORDERS_SUCCESS';
export const LIST_MF_PURCHASE_ORDERS_FAILURE =
  'LIST_MF_PURCHASE_ORDERS_FAILURE';

// To sell purchase order
export const CREATE_MF_REDEMPTION_LOADING = 'CREATE_MF_REDEMPTION_LOADING';
export const CREATE_MF_REDEMPTION_SUCCESS = 'CREATE_MF_REDEMPTION_SUCCESS';
export const CREATE_MF_REDEMPTION_FAILURE = 'CREATE_MF_REDEMPTION_FAILURE';

// Fetch Bank Account Status Token
export const GET_BANK_STATUS_TOKEN_LOADING = 'GET_BANK_STATUS_TOKEN_LOADING';
export const GET_BANK_STATUS_TOKEN_SUCCESS = 'GET_BANK_STATUS_TOKEN_SUCCESS';
export const GET_BANK_STATUS_TOKEN_FAILURE = 'GET_BANK_STATUS_TOKEN_FAILURE';

// Verify Bank Account Status
export const CHECK_BANK_STATUS_LOADING = 'CHECK_BANK_STATUS_LOADING';
export const CHECK_BANK_STATUS_SUCCESS = 'CHECK_BANK_STATUS_SUCCESS';
export const CHECK_BANK_STATUS_FAILURE = 'CHECK_BANK_STATUS_FAILURE';

// To get investor onboarding list
export const GET_INVESTONBOARDING_LOADING = 'GET_INVESTONBOARDING_LOADING';
export const GET_INVESTONBOARDING_SUCCESS = 'GET_INVESTONBOARDING_SUCCESS';
export const GET_INVESTONBOARDING_FAILURE = 'GET_INVESTONBOARDING_FAILURE';

// Insert invest details
export const INVEST_INSERT_LOADING = 'INVEST_INSERT_LOADING';
export const INVEST_INSERT_SUCCESS = 'INVEST_INSERT_SUCCESS';
export const INVEST_INSERT_FAILURE = 'INVEST_INSERT_FAILURE';

// Update invest details
export const INVEST_UPDATE_LOADING = 'INVEST_UPDATE_LOADING';
export const INVEST_UPDATE_SUCCESS = 'INVEST_UPDATE_SUCCESS';
export const INVEST_UPDATE_FAILURE = 'INVEST_UPDATE_FAILURE';

// To get the invest purchase list
export const GET_INVEST_LOADING = 'GET_INVEST_LOADING';
export const GET_INVEST_SUCCESS = 'GET_INVEST_SUCCESS';
export const GET_INVEST_FAILURE = 'GET_INVEST_FAILURE';

// To get mf listing
export const GET_MF_LOADING = 'GET_MF_LOADING';
export const GET_MF_SUCCESS = 'GET_MF_SUCCESS';
export const GET_MF_FAILURE = 'GET_MF_FAILURE';

// To get AMC'S list
export const GET_AMCLIST_LOADING = 'GET_AMCLIST_LOADING';
export const GET_AMCLIST_SUCCESS = 'GET_AMCLIST_SUCCESS';
export const GET_AMCLIST_FAILURE = 'GET_AMCLIST_FAILURE';

// Create purchase
export const CREATE_PURCHASE_LOADING = 'CREATE_PURCHASE_LOADING';
export const CREATE_PURCHASE_SUCCESS = 'CREATE_PURCHASE_SUCCESS';
export const CREATE_PURCHASE_FAILURE = 'CREATE_PURCHASE_FAILURE';

// Update purchase
export const UPDATE_PURCHASE_LOADING = 'UPDATE_PURCHASE_LOADING';
export const UPDATE_PURCHASE_SUCCESS = 'UPDATE_PURCHASE_SUCCESS';
export const UPDATE_PURCHASE_FAILURE = 'UPDATE_PURCHASE_FAILURE';

// To update redemption status
export const UPDATE_MF_REDEMPTION_LOADING = 'UPDATE_MF_REDEMPTION_LOADING';
export const UPDATE_MF_REDEMPTION_SUCCESS = 'UPDATE_MF_REDEMPTION_SUCCESS';
export const UPDATE_MF_REDEMPTION_FAILURE = 'UPDATE_MF_REDEMPTION_FAILURE';

// To insert sell redemption object
export const INSERT_MF_REDEMPTION_DATA_LOADING =
  'INSERT_MF_REDEMPTION_DATA_LOADING';
export const INSERT_MF_REDEMPTION_DATA_SUCCESS =
  'INSERT_MF_REDEMPTION_DATA_SUCCESS';
export const INSERT_MF_REDEMPTION_DATA_FAILURE =
  'INSERT_MF_REDEMPTION_DATA_FAILURE';

export const FIND_GOAL_NAME_LOADING = 'FIND_GOAL_NAME_LOADING';
export const FIND_GOAL_NAME_SUCCESS = 'FIND_GOAL_NAME_SUCCESS';
export const FIND_GOAL_NAME_FAILURE = 'INSERT_MF_REDEMPTION_DATA_FAILURE';

export const GET_REDEMP_SWITCH_STATUS_LOADING =
  'GET_REDEMP_SWITCH_STATUS_LOADING';
export const GET_REDEMP_SWITCH_STATUS_SUCCESS =
  'GET_REDEMP_SWITCH_STATUS_SUCCESS';
export const GET_REDEMP_SWITCH_STATUS_FAILURE =
  'GET_REDEMP_SWITCH_STATUS_FAILURE';

export const MF_PERFORMANCE_LIST_LOADING = 'MF_PERFORMANCE_LIST_LOADING';
export const MF_PERFORMANCE_LIST_SUCCESS = 'MF_PERFORMANCE_LIST_SUCCESS';
export const MF_PERFORMANCE_LIST_FAILURE = 'MF_PERFORMANCE_LIST_FAILURE';

// For Gold and Silver Module

export const GET_GOLD_TOKEN_LOADING = 'GET_GOLD_TOKEN_LOADING';
export const GET_GOLD_TOKEN_SUCCESS = 'GET_GOLD_TOKEN_SUCCESS';
export const GET_GOLD_TOKEN_FAILURE = 'GET_GOLD_TOKEN_FAILURE';

export const GET_GOLD_PRODUCTS_LOADING = 'GET_GOLD_PRODUCTS_LOADING';
export const GET_GOLD_PRODUCTS_SUCCESS = 'GET_GOLD_PRODUCTS_SUCCESS';
export const GET_GOLD_PRODUCTS_FAILURE = 'GET_GOLD_PRODUCTS_FAILURE';

export const ADD_GOLD_ADDRESS_LOADING = 'ADD_GOLD_ADDRESS_LOADING';
export const ADD_GOLD_ADDRESS_SUCCESS = 'ADD_GOLD_ADDRESS_SUCCESS';
export const ADD_GOLD_ADDRESS_FAILURE = 'ADD_GOLD_ADDRESS_FAILURE';

export const ORDER_GOLD_DELIVERY_LOADING = 'ORDER_GOLD_DELIVERY_LOADING';
export const ORDER_GOLD_DELIVERY_SUCCESS = 'ORDER_GOLD_DELIVERY_SUCCESS';
export const ORDER_GOLD_DELIVERY_FAILURE = 'ORDER_GOLD_DELIVERY_FAILURE';

export const GET_GOLD_PASSBOOK_LOADING = 'GET_GOLD_PASSBOOK_LOADING';
export const GET_GOLD_PASSBOOK_SUCCESS = 'GET_GOLD_PASSBOOK_SUCCESS';
export const GET_GOLD_PASSBOOK_FAILURE = 'GET_GOLD_PASSBOOK_FAILURE';

export const GET_GOLD_ADDRESS_LIST_LOADING = 'GET_GOLD_ADDRESS_LIST_LOADING';
export const GET_GOLD_ADDRESS_LIST_SUCCESS = 'GET_GOLD_ADDRESS_LIST_SUCCESS';
export const GET_GOLD_ADDRESS_LIST_FAILURE = 'GET_GOLD_ADDRESS_LIST_FAILURE';

export const GET_STATES_LOADING = 'GET_STATES_LOADING';
export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAILURE = 'GET_STATES_FAILURE';

export const GET_CITIES_LOADING = 'GET_CITIES_LOADING';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';

export const DELETE_GOLD_ADDRESS_LOADING = 'DELETE_GOLD_ADDRESS_LOADING';
export const DELETE_GOLD_ADDRESS_SUCCESS = 'DELETE_GOLD_ADDRESS_SUCCESS';
export const DELETE_GOLD_ADDRESS_FAILURE = 'DELETE_GOLD_ADDRESS_FAILURE';

export const GOLD_ADD_TO_CART = 'GOLD_ADD_TO_CART';
export const GOLD_REMOVE_FROM_CART = 'GOLD_REMOVE_FROM_CART';
export const GOLD_ADD_QUANTITY = 'GOLD_ADD_QUANTITY';
export const GOLD_REMOVE_QUANTITY = 'GOLD_REMOVE_QUANTITY';
export const GOLD_EMPTY_CART = 'GOLD_EMPTY_CART';

export const USER_ADDRESS_LIST_LOADING = 'USER_ADDRESS_LIST_LOADING';
export const USER_ADDRESS_LIST_SUCCESS = 'USER_ADDRESS_LIST_SUCCESS';
export const USER_ADDRESS_LIST_FAILURE = 'USER_ADDRESS_LIST_FAILURE';

export const USER_DELETE_ADDRESS_LOADING = 'USER_DELETE_ADDRESS_LOADING';
export const USER_DELETE_ADDRESS_SUCCESS = 'USER_DELETE_ADDRESS_SUCCESS';
export const USER_DELETE_ADDRESS_FAILURE = 'USER_DELETE_ADDRESS_FAILURE';

export const USER_DELIVERY_ORDER_LOADING = 'USER_DELIVERY_ORDER_LOADING';
export const USER_DELIVERY_ORDER_SUCCESS = 'USER_DELIVERY_ORDER_SUCCESS';
export const USER_DELIVERY_ORDER_FAILURE = 'USER_DELIVERY_ORDER_FAILURE';

export const GET_GOLD_SILVER_RATES_LOADING = 'GET_GOLD_SILVER_RATES_LOADING';
export const GET_GOLD_SILVER_RATES_SUCCESS = 'GET_GOLD_SILVER_RATES_SUCCESS';
export const GET_GOLD_SILVER_RATES_FAILURE = 'GET_GOLD_SILVER_RATES_FAILURE';

export const GET_GOLD_SILVER_BALANCE_LOADING =
  'GET_GOLD_SILVER_BALANCE_LOADING';
export const GET_GOLD_SILVER_BALANCE_SUCCESS =
  'GET_GOLD_SILVER_BALANCE_SUCCESS';
export const GET_GOLD_SILVER_BALANCE_FAILURE =
  'GET_GOLD_SILVER_BALANCE_FAILURE';

export const ADD_NEW_BANK_LOADING = 'ADD_NEW_BANK_LOADING';
export const ADD_NEW_BANK_SUCCESS = 'ADD_NEW_BANK_SUCCESS';
export const ADD_NEW_BANK_FAILURE = 'ADD_NEW_BANK_FAILURE';

export const LIST_BANKS_FLOADING = 'LIST_BANKS_FLOADING';
export const LIST_BANKS_SUCCESS = 'LIST_BANKS_SUCCESS';
export const LIST_BANKS_FAILURE = 'LIST_BANKS_FAILURE';

export const SELL_GOLD_SILVER_LOADING = 'SELL_GOLD_SILVER_LOADING';
export const SELL_GOLD_SILVER_SUCCESS = 'SELL_GOLD_SILVER_SUCCESS';
export const SELL_GOLD_SILVER_FAILURE = 'SELL_GOLD_SILVER_FAILURE';

export const INSERT_BANK_DETAILS_LOADING = 'INSERT_BANK_DETAILS_LOADING';
export const INSERT_BANK_DETAILS_SUCCESS = 'INSERT_BANK_DETAILS_SUCCESS';
export const INSERT_BANK_DETAILS_FAILURE = 'INSERT_BANK_DETAILS_FAILURE';

export const USER_SELL_GOLD_SILVER_LOADING = 'USER_SELL_GOLD_SILVER_LOADING';
export const USER_SELL_GOLD_SILVER_SUCCESS = 'USER_SELL_GOLD_SILVER_SUCCESS';
export const USER_SELL_GOLD_SILVER_FAILURE = 'USER_SELL_GOLD_SILVER_FAILURE';

// Verify Bank Account Status
export const GOLD_BANK_STATUS_LOADING = 'GOLD_BANK_STATUS_LOADING';
export const GOLD_BANK_STATUS_SUCCESS = 'GOLD_BANK_STATUS_SUCCESS';
export const GOLD_BANK_STATUS_FAILURE = 'GOLD_BANK_STATUS_FAILURE';

export const BUY_GOLD_SILVER_LOADING = 'BUY_GOLD_SILVER_LOADING';
export const BUY_GOLD_SILVER_SUCCESS = 'BUY_GOLD_SILVER_SUCCESS';
export const BUY_GOLD_SILVER_FAILURE = 'BUY_GOLD_SILVER_FAILURE';

export const CHECK_INVESTORE_GOLDSILVER_LOADING =
  'CHECK_INVESTORE_GOLDSILVER_LOADING';
export const CHECK_INVESTORE_GOLDSILVER_SUCCESS =
  'CHECK_INVESTORE_GOLDSILVER_SUCCESS';
export const CHECK_INVESTORE_GOLDSILVER_FAILURE =
  'CHECK_INVESTORE_GOLDSILVER_FAILURE';

export const USER_BUY_GOLD_SILVER_LOADING = 'USER_BUY_GOLD_SILVER_LOADING';
export const USER_BUY_GOLD_SILVER_SUCCESS = 'USER_BUY_GOLD_SILVER_SUCCESS';
export const USER_BUY_GOLD_SILVER_FAILURE = 'USER_BUY_GOLD_SILVER_FAILURE';

export const ADD_NEW_USER_LOADING = 'ADD_NEW_USER_LOADING';
export const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
export const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE';

export const GIFT_RECIPENT_LOADING = 'GIFT_RECIPENT_LOADING';
export const GIFT_RECIPENT_SUCCESS = 'GIFT_RECIPENT_SUCCESS';
export const GIFT_RECIPENT_FAILURE = 'GIFT_RECIPENT_FAILURE';

//  Tansfer
export const TRANSFER_GOLD_SILVER_LOADING = 'TRANSFER_GOLD_SILVER_LOADING';
export const TRANSFER_GOLD_SILVER_SUCCESS = 'TRANSFER_GOLD_SILVER_SUCCESS';
export const TRANSFER_GOLD_SILVER_FAILURE = 'TRANSFER_GOLD_SILVER_FAILURE';

// User Gift
export const CHECK_GIFT_LOADING = 'CHECK_GIFT_LOADING';
export const CHECK_GIFT_SUCCESS = 'CHECK_GIFT_SUCCESS';
export const CHECK_GIFT_FAILURE = 'CHECK_GIFT_FAILURE';

export const GET_CONTACT_NUMBER_LOADING = 'GET_CONTACT_NUMBER_LOADING';
export const GET_CONTACT_NUMBER_SUCCESS = 'GET_CONTACT_NUMBER_SUCCESS';
export const GET_CONTACT_NUMBER_FAILURE = 'GET_CONTACT_NUMBER_FAILURE';

export const GOLD_OTP_VERIFY_LOADING = 'GOLD_OTP_VERIFY_LOADING';
export const GOLD_OTP_VERIFY_SUCCESS = 'GOLD_OTP_VERIFY_SUCCESS';
export const GOLD_OTP_VERIFY_FAILURE = 'GOLD_OTP_VERIFY_FAILURE';

export const GET_MAX_REDEEM_AMOUNT_UNITS_LOADING =
  'GET_MAX_REDEEM_AMOUNT_UNITS_LOADING';
export const GET_MAX_REDEEM_AMOUNT_UNITS_SUCCESS =
  'GET_MAX_REDEEM_AMOUNT_UNITS_SUCCESS';
export const GET_MAX_REDEEM_AMOUNT_UNITS_FAILURE =
  'GET_MAX_REDEEM_AMOUNT_UNITS_FAILURE';

export const GET_FOLIO_LIST_LOADING = 'GET_FOLIO_LIST_LOADING';
export const GET_FOLIO_LIST_SUCCESS = 'GET_FOLIO_LIST_SUCCESS';
export const GET_FOLIO_LIST_FAILURE = 'GET_FOLIO_LIST_FAILURE';

// User passbook
export const GET_PASSBOOK_LOADING = 'GET_PASSBOOK_LOADING';
export const GET_PASSBOOK_SUCCESS = 'GET_PASSBOOK_SUCCESS';
export const GET_PASSBOOK_FAILURE = 'GET_PASSBOOK_FAILURE';

// User resend otp
export const RESEND_OTP_LOADING = 'RESEND_OTP_LOADING';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';

// User BOUGHT SELL DETAILS FAILURE
export const BOUGHT_SELL_DETAILS_LOADING = 'BOUGHT_SELL_DETAILS_LOADING';
export const BOUGHT_SELL_DETAILS_SUCCESS = 'BOUGHT_SELL_DETAILS_SUCCESS';
export const BOUGHT_SELL_DETAILS_FAILURE = 'BOUGHT_SELL_DETAILS_FAILURE';

// User passbook invoice
export const GET_PASSBOOK_INVOICE_LOADING = 'GET_PASSBOOK_INVOICE_LOADING';
export const GET_PASSBOOK_INVOICE_SUCCESS = 'GET_PASSBOOK_INVOICE_SUCCESS';
export const GET_PASSBOOK_INVOICE_FAILURE = 'GET_PASSBOOK_INVOICE_FAILURE';

// User passbook payout details
export const GET_PASSBOOK_PAYOUT_DETAILS_LOADING =
  'GET_PASSBOOK_PAYOUT_DETAILS_LOADING';
export const GET_PASSBOOK_PAYOUT_DETAILS_SUCCESS =
  'GET_PASSBOOK_PAYOUT_DETAILS_SUCCESS';
export const GET_PASSBOOK_PAYOUT_DETAILS_FAILURE =
  'GET_PASSBOOK_PAYOUT_DETAILS_FAILURE';

// User passbook gift details
export const GET_PASSBOOK_GIFT_DETAILS_LOADING =
  'GET_PASSBOOK_GIFT_DETAILS_LOADING';
export const GET_PASSBOOK_GIFT_DETAILS_SUCCESS =
  'GET_PASSBOOK_GIFT_DETAILS_SUCCESS';
export const GET_PASSBOOK_GIFT_DETAILS_FAILURE =
  'GET_PASSBOOK_GIFT_DETAILS_FAILURE';

// User passbook with draw gift details
export const GET_PASSBOOK_WITH_DRAW_GIFT_LOADING =
  'GET_PASSBOOK_WITH_DRAW_GIFT_LOADING';
export const GET_PASSBOOK_WITH_DRAW_GIFT_SUCCESS =
  'GET_PASSBOOK_WITH_DRAW_GIFT_SUCCESS';
export const GET_PASSBOOK_WITH_DRAW_GIFT_FAILURE =
  'GET_PASSBOOK_WITH_DRAW_GIFT_FAILURE';

// User get all bank list
export const GET_ALL_BANK_LIST_LOADING = 'GET_ALL_BANK_LIST_LOADING';
export const GET_ALL_BANK_LIST_SUCCESS = 'GET_ALL_BANK_LIST_SUCCESS';
export const GET_ALL_BANK_LIST_FAILURE = 'GET_ALL_BANK_LIST_FAILURE';

// User get passbook delivery details  list
export const PASSBOOK_DELIVERY_DETAILS_LOADING =
  'PASSBOOK_DELIVERY_DETAILS_LOADING';
export const PASSBOOK_DELIVERY_DETAILS_SUCCESS =
  'PASSBOOK_DELIVERY_DETAILS_SUCCESS';
export const PASSBOOK_DELIVERY_DETAILS_FAILURE =
  'PASSBOOK_DELIVERY_DETAILS_FAILURE';

// User bank account exists
export const BANK_ACCOUNT_EXISTS_LOADING = 'BANK_ACCOUNT_EXISTS_LOADING';
export const BANK_ACCOUNT_EXISTS_SUCCESS = 'BANK_ACCOUNT_EXISTS_SUCCESS';
export const BANK_ACCOUNT_EXISTS_FAILURE = 'BANK_ACCOUNT_EXISTS_FAILURE';

// User bank Payment Completion
export const PAYMENT_COMPLETION_LOADING = 'PAYMENT_COMPLETION_LOADING';
export const PAYMENT_COMPLETION_SUCCESS = 'PAYMENT_COMPLETION_SUCCESS';
export const PAYMENT_COMPLETION_FAILURE = 'PAYMENT_COMPLETION_FAILURE';

// User PASSBOOK delivery details Invoice
export const DELIVERY_DETAILS_INVOICE_LOADING =
  'DELIVERY_DETAILS_INVOICE_LOADING';
export const DELIVERY_DETAILS_INVOICE_SUCCESS =
  'DELIVERY_DETAILS_INVOICE_SUCCESS';
export const DELIVERY_DETAILS_INVOICE_FAILURE =
  'DELIVERY_DETAILS_INVOICE_FAILURE';

// Dashboard High Spending
export const HIGH_SPENDING_LOADING = 'HIGH_SPENDING_LOADING';
export const HIGH_SPENDING_SUCCESS = 'HIGH_SPENDING_SUCCESS';
export const HIGH_SPENDING_FAILURE = 'HIGH_SPENDING_FAILURE';

// Create order id
export const CREATE_ORDER_API_LOADING = 'CREATE_ORDER_API_LOADING';
export const CREATE_ORDER_API_SUCCESS = 'CREATE_ORDER_API_SUCCESS';
export const CREATE_ORDER_API_FAILURE = 'CREATE_ORDER_API_FAILURE';

//  To get investor user Data
export const GET_INVESTOR_USER_DATA_LOADING = 'GET_INVESTOR_USER_DATA_LOADING';
export const GET_INVESTOR_USER_DATA_SUCCESS = 'GET_INVESTOR_USER_DATA_SUCCESS';
export const GET_INVESTOR_USER_DATA_FAILURE = 'GET_INVESTOR_USER_DATA_FAILURE';

// GET TICKET CATEGORY
export const GET_TICKET_CATEGORY_LOADING = 'GET_TICKET_CATEGORY_LOADING';
export const GET_TICKET_CATEGORY_SUCCESS = 'GET_TICKET_CATEGORY_SUCCESS';
export const GET_TICKET_CATEGORY_FAILURE = 'GET_TICKET_CATEGORY_FAILURE';

// POST CREATE TICKET
export const CREATE_TICKET_LOADING = 'CREATE_TICKET_LOADING';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAILURE = 'CREATE_TICKET_FAILURE';

// GET TICKET LIST OF PARTICULAR USER
export const GET_TICKET_LIST_LOADING = 'GET_TICKET_LIST_LOADING';
export const GET_TICKET_LIST_SUCCESS = 'GET_TICKET_LIST_SUCCESS';
export const GET_TICKET_LIST_FAILURE = 'GET_TICKET_LIST_FAILURE';

// GET  FINANCIALSNAP for user
export const GET_FINANCIALSNAP_LOADING = 'GET_FINANCIALSNAP_LOADING';
export const GET_FINANCIALSNAP_SUCCESS = 'GET_FINANCIALSNAP_SUCCESS';
export const GET_FINANCIALSNAP_FAILURE = 'GET_FINANCIALSNAP_FAILURE';

// GET  nearbyoffers for user
export const GET_NEARBYOFFERS_LOADING = 'GET_NEARBYOFFERS_LOADING';
export const GET_NEARBYOFFERS_SUCCESS = 'GET_NEARBYOFFERS_SUCCESS';
export const GET_NEARBYOFFERS_FAILURE = 'GET_NEARBYOFFERS_FAILURE';

// GET NOTIFICATION LIST
export const GET_NOTIFICATION_LIST_LOADING = 'GET_NOTIFICATION_LIST_LOADING';
export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS';
export const GET_NOTIFICATION_LIST_FAILURE = 'GET_NOTIFICATION_LIST_FAILURE';

// Get Gold Silver Purchase Amount
export const GET_GOLD_SILVER_PURCHASE_AMOUNT_LOADING =
  'GET_GOLD_SILVER_PURCHASE_AMOUNT_LOADING';
export const GET_GOLD_SILVER_PURCHASE_AMOUNT_SUCCESS =
  'GET_GOLD_SILVER_PURCHASE_AMOUNT_SUCCESS';
export const GET_GOLD_SILVER_PURCHASE_AMOUNT_FAILURE =
  'GET_GOLD_SILVER_PURCHASE_AMOUNT_FAILURE';

export const GET_KYCSTATUS_LOADING = 'GET_KYCSTATUS_LOADING';
export const GET_KYCSTATUS_FAILURE = 'GET_KYCSTATUS_FAILURE';
export const GET_KYCSTATUS_SUCCESS = 'GET_KYCSTATUS_SUCCESS';

// New Onboarding integration
export const KYC_STATUS_LOADING = 'KYC_STATUS_LOADING';
export const KYC_STATUS_FAILURE = 'KYC_STATUS_FAILURE';
export const KYC_STATUS_SUCCESS = 'KYC_STATUS_SUCCESS';

export const PAN_VERIFY_LOADING = 'PAN_VERIFY_LOADING';
export const PAN_VERIFY_FAILURE = 'PAN_VERIFY_FAILURE';
export const PAN_VERIFY_SUCCESS = 'PAN_VERIFY_SUCCESS';

export const PAN_DETAILS_LOADING = 'PAN_DETAILS_LOADING';
export const PAN_DETAILS_FAILURE = 'PAN_DETAILS_FAILURE';
export const PAN_DETAILS_SUCCESS = 'PAN_DETAILS_SUCCESS';

export const BASIC_DETAILS_LOADING = 'BASIC_DETAILS_LOADING';
export const BASIC_DETAILS_SUCCESS = 'BASIC_DETAILS_SUCCESS';
export const BASIC_DETAILS_FAILURE = 'BASIC_DETAILS_FAILURE';

export const ZIPCODE_VERIFY_LOADING = 'ZIPCODE_VERIFY_LOADING';
export const ZIPCODE_VERIFY_SUCCESS = 'ZIPCODE_VERIFY_SUCCESS';
export const ZIPCODE_VERIFY_FAILURE = 'ZIPCODE_VERIFY_FAILURE';

export const UPDATEINVESTOR_ADDRESS_LOADING = 'UPDATEINVESTOR_ADDRESS_LOADING';
export const UPDATEINVESTOR_ADDRESS_SUCCESS = 'UPDATEINVESTOR_ADDRESS_SUCCESS';
export const UPDATEINVESTOR_ADDRESS_FAILURE = 'UPDATEINVESTOR_ADDRESS_FAILURE';

export const ADD_NOMINEE_LOADING = 'ADD_NOMINEE_LOADING';
export const ADD_NOMINEE_SUCCESS = 'ADD_NOMINEE_SUCCESS';
export const ADD_NOMINEE_FAILURE = 'ADD_NOMINEE_FAILURE';

export const VERIFY_IFSC_LOADING = 'VERIFY_IFSC_LOADING';
export const VERIFY_IFSC_SUCCESS = 'VERIFY_IFSC_SUCCESS';
export const VERIFY_IFSC_FAILURE = 'VERIFY_IFSC_FAILURE';

export const ADDINVESTOR_BANK_LOADING = 'ADDINVESTOR_BANK_LOADING';
export const ADDINVESTOR_BANK_SUCCESS = 'ADDINVESTOR_BANK_SUCCESS';
export const ADDINVESTOR_BANK_FAILURE = 'ADDINVESTOR_BANK_FAILURE';

export const VALIDATE_BANK_LOADING = 'VALIDATE_BANK_LOADING';
export const VALIDATE_BANK_SUCCESS = 'VALIDATE_BANK_SUCCESS';
export const VALIDATE_BANK_FAILURE = 'VALIDATE_BANK_FAILURE';

export const ADD_MANDATE_LOADING = 'ADD_MANDATE_LOADING';
export const ADD_MANDATE_FAILURE = 'ADD_MANDATE_FAILURE';
export const ADD_MANDATE_SUCCESS = 'ADD_MANDATE_SUCCESS';

export const SAVE_MANDATE_LOADING = 'SAVE_MANDATE_LOADING';
export const SAVE_MANDATE_FAILURE = 'SAVE_MANDATE_FAILURE';
export const SAVE_MANDATE_SUCCESS = 'SAVE_MANDATE_SUCCESS';

export const GET_INVDETAILS_LOADING = 'GET_INVDETAILS_LOADING';
export const GET_INVDETAILS_FAILURE = 'GET_INVDETAILS_FAILURE';
export const GET_INVDETAILS_SUCCESS = 'GET_INVDETAILS_SUCCESS';

export const SIP_ADD_SUCCESS = 'SIP_ADD_SUCCESS';
export const SIP_ADD_LOADING = 'SIP_ADD_LOADING';
export const SIP_ADD_FAILURE = 'SIP_ADD_FAILURE';

export const SIP_DEACTIVATE_SUCCESS = 'SIP_DEACTIVATE_SUCCESS';
export const SIP_DEACTIVATE_LOADING = 'SIP_DEACTIVATE_LOADING';
export const SIP_DEACTIVATE_FAILURE = 'SIP_DEACTIVATE_FAILURE';

export const SIP_LIST_LOADING = 'SIP_LIST_LOADING';
export const SIP_LIST_SUCCESS = 'SIP_LIST_SUCCESS';
export const SIP_LIST_FAILURE = 'SIP_LIST_FAILURE';

export const MANDATE_LIST_LOADING = 'MANDATE_LIST_LOADING';
export const MANDATE_LIST_SUCCESS = 'MANDATE_LIST_SUCCESS';
export const MANDATE_LIST_FAILURE = 'MANDATE_LIST_FAILURE';

export const MANDATE_LIMIT_LOADING = 'MANDATE_LIMIT_LOADING';
export const MANDATE_LIMIT_SUCCESS = 'MANDATE_LIMIT_SUCCESS';
export const MANDATE_LIMIT_FAILURE = 'MANDATE_LIMIT_FAILURE';

// Fd Register

export const UPDATE_KYCDOC_LOADING = 'UPDATE_KYCDOC_LOADING';
export const UPDATE_KYCDOC_SUCCESS = 'UPDATE_KYCDOC_SUCCESS';
export const UPDATE_KYCDOC_FAILURE = 'UPDATE_KYCDOC_FAILURE';

export const UPDATE_KYCVIDEO_LOADING = 'UPDATE_KYCVIDEO_LOADING';
export const UPDATE_KYCVIDEO_SUCCESS = 'UPDATE_KYCVIDEO_SUCCESS';
export const UPDATE_KYCVIDEO_FAILURE = 'UPDATE_KYCVIDEO_FAILURE';

export const GET_ESIGNURL_LOADING = 'GET_ESIGNURL_LOADING';
export const GET_ESIGNURL_SUCCESS = 'GET_ESIGNURL_SUCCESS';
export const GET_ESIGNURL_FAILURE = 'GET_ESIGNURL_FAILURE';

export const SAVE_ESIGNDATA_LOADING = 'SAVE_ESIGNDATA_LOADING';
export const SAVE_ESIGNDATA_SUCCESS = 'SAVE_ESIGNDATA_SUCCESS';
export const SAVE_ESIGNDATA_FAILURE = 'SAVE_ESIGNDATA_FAILURE';

export const GET_INVESTORDATA_LOADINNG = 'GET_INVESTORDATA_LOADINNG';
export const GET_INVESTORDATA_SUCCESS = 'GET_INVESTORDATA_SUCCESS';
export const GET_INVESTORDATA_FAILURE = 'GET_INVESTORDATA_FAILURE';

export const ADD_FD_VERIFICATION_REGISTER_LOADING =
  'ADD_FD_VERIFICATION_REGISTER_LOADING';
export const ADD_FD_VERIFICATION_REGISTER_SUCCESS =
  'ADD_FD_VERIFICATION_REGISTER_SUCCESS';
export const ADD_FD_VERIFICATION_REGISTER_FAILURE =
  'ADD_FD_VERIFICATION_REGISTER_FAILURE';

export const USER_CODE_LOADING = 'USER_CODE_LOADING';
export const USER_CODE_SUCCESS = 'USER_CODE_SUCCESS';
export const USER_CODE_FAILURE = 'USER_CODE_FAILURE';

export const MANDATE_PAYMENTRESPONSE_SUCCESS =
  'MANDATE_PAYMENTRESPONSE_SUCCESS';
export const MANDATE_PAYMENTRESPONSE_LOADING =
  'MANDATE_PAYMENTRESPONSE_LOADING';
export const MANDATE_PAYMENTRESPONSE_FAILURE =
  'MANDATE_PAYMENTRESPONSE_FAILURE';

export const INVEST_PAYMENTRESPONSE_SUCCESS = 'INVEST_PAYMENTRESPONSE_SUCCESS';
export const INVEST_PAYMENTRESPONSE_LOADING = 'INVEST_PAYMENTRESPONSE_LOADING';
export const INVEST_PAYMENTRESPONSE_FAILURE = 'INVEST_PAYMENTRESPONSE_FAILURE';

export const CLEAR_ONBOARDING_SUCCESS = 'CLEAR_ONBOARDING_SUCCESS';

// MF FILER

export const MUTUAL_FUND_FITLER = 'MUTUAL_FUND_FILTER';
export const CLEAR_MUTUAL_FUND_FILTER = 'CLEAR_MUTUAL_FUND_FILTER';

// FILTER COLOR

export const FILTER_WHITE_COLOR = 'FILTER_WHITE_COLOR';
export const FILTER_CYAN_COLOR = 'FILTER_CYAN_COLOR';

export const FUND_CATEGORY = 'FUND_CATEGORY';
export const SELECT_ID = 'SELECT_ID';
export const FUND_SUB_CATEGORY = 'FUND_SUB_CATEGORY';

// Global KYC PAN

export const GET_KYC_PAN_LOADING = 'GET_KYC_PAN_LOADING';
export const GET_KYC_PAN_SUCCESS = 'GET_KYC_PAN_SUCCESS';
export const GET_KYC_PAN_FAILURE = 'GET_KYC_PAN_FAILURE';

// Get KYC PAN DETAILS
export const GET_PAN_DETAILS_LOADING = 'GET_PAN_DETAILS_LOADING';
export const GET_PAN_DETAILS_SUCCESS = 'GET_PAN_DETAILS_SUCCESS';
export const GET_PAN_DETAILS_FAILURE = 'GET_PAN_DETAILS_FAILURE';

// Get Wealth Value

export const WEALTH_VALUE_LOADING = 'WEALTH_VALUE_LOADING';
export const WEALTH_VALUE_SUCCESS = 'WEALTH_VALUE_SUCCESS';
export const WEALTH_VALUE_FAILURE = 'WEALTH_VALUE_FAILURE';

// To get financial goal

export const GET_SAVING_PLANNER_SUCCESS = 'GET_SAVING_PLANNER_SUCCESS';


// To get new goal categories

export const GET_NWGOALCATEGORIES_SUCCESS = 'GET_NWGOALCATEGORIES_SUCCESS';

// Constant for mutual fund bundle
export const GET_MF_LIST_BUNDLE_LOADING = 'GET_MF_LIST_BUNDLE_LOADING';
export const GET_MF_LIST_BUNDLE_SUCCESS = 'GET_MF_LIST_BUNDLE_SUCCESS';
export const GET_MF_LIST_BUNDLE_FAILURE = 'GET_MF_LIST_BUNDLE_FAILURE';

export const CHECK_PAYMENT_POSTBACK_LOADING = 'CHECK_PAYMENT_POSTBACK_LOADING';
export const CHECK_PAYMENT_POSTBACK_SUCCESS = 'CHECK_PAYMENT_POSTBACK_SUCCESS';
export const CHECK_PAYMENT_POSTBACK_FAILURE = 'CHECK_PAYMENT_POSTBACK_FAILURE';

// GET GOAL API

export const GET_GOAL_LISTING_LOADING = 'GET_GOAL_LISTING_LOADING';
export const GET_GOAL_LISTING_SUCCESS = 'GET_GOAL_LISTING_SUCCESS';
export const GET_GOAL_LISTING_FAILURE = 'GET_GOAL_LISTING_FAILURE';

export const USER_DATA_LOGOUT = 'USER_DATA_LOGOUT';
export const USER_DATA_LOGIN = 'USER_DATA_LOGIN';

// //loader
// export const LOADER = 'LOADER';
// export const SHOW_TOAST = 'SHOW_TOAST';
// export const HIDE_TOAST = 'HIDE_TOAST';

export const BBPS_URL_LOADING = 'BBPS_URL_LOADING';
export const BBPS_URL_FAILURE = 'BBPS_URL_FAILURE';
export const BBPS_URL_SUCCESS = 'BBPS_URL_SUCCESS';
export const GET_FINANCIAL_GOAL_WEALTH_LOADING =
  'GET_FINANCIAL_GOAL_WEALTH_LOADING';
export const GET_FINANCIAL_GOAL_WEALTH_SUCCESS =
  'GET_FINANCIAL_GOAL_WEALTH_SUCCESS';
export const GET_FINANCIAL_GOAL_WEALTH_FAILURE =
  'GET_FINANCIAL_GOAL_WEALTH_FAILURE';

export const ASSET_TYPE_LOADING = 'ASSET_TYPE_LOADING';
export const ASSET_TYPE_SUCCESS = 'ASSET_TYPE_SUCCESS';
export const ASSET_TYPE_FAILURE = 'ASSET_TYPE_FAILURE';

// Goal Based Wealth

export const GOAL_BASED_WEALTH_LOADING = 'GOAL_BASED_WEALTH_LOADING';
export const GOAL_BASED_WEALTH_SUCCESS = 'GOAL_BASED_WEALTH_SUCCESS';
export const GOAL_BASED_WEALTH_FAILURE = 'GOAL_BASED_WEALTH_FAILURE';
//notifications
export const GET_NOTIFICATIONCOUNT_LOADING = 'GET_NOTIFICATIONCOUNT_LOADING';
export const GET_NOTIFICATIONCOUNT_FAILURE = 'GET_NOTIFICATIONCOUNT_FAILURE';
export const GET_NOTIFICATIONCOUNT_SUCCESS = 'GET_NOTIFICATIONCOUNT_SUCCESS';

export const GET_READNOTIFICATION_LOADING = 'GET_READNOTIFICATION_LOADING';
export const GET_READNOTIFICATION_FAILURE = 'GET_READNOTIFICATION_FAILURE';
export const GET_READNOTIFICATION_SUCCESS = 'GET_READNOTIFICATION_SUCCESS';

export const GET_AGE = 'GET_AGE'


export const POST_REFERAL_CODE_LOADING = 'POST_REFERAL_CODE_LOADING';
export const POST_REFERAL_CODE_SUCCESS = 'POST_REFERAL_CODE_SUCCESS';
export const POST_REFERAL_CODE_FAILURE = 'POST_REFERAL_CODE_FAILURE';


export const CLAIM_BONUS_LOADING = 'CLAIM_BONUS_LOADING';
export const CLAIM_BONUS_SUCCESS = 'CLAIM_BONUS_SUCCESS';
export const CLAIM_BONUS_FAILURE = 'CLAIM_BONUS_FAILURE';

export const SMALLCASE_HOLDING_LOADING = 'SMALLCASE_HOLDING_LOADING';
export const SMALLCASE_HOLDING_SUCCESS = 'SMALLCASE_HOLDING_SUCCESS';
export const SMALLCASE_HOLDING_FAILURE = 'SMALLCASE_HOLDING_FAILURE';
export const PORTFOLIO_TYPE_LOADING = 'PORTFOLIO_TYPE_LOADING';
export const PORTFOLIO_TYPE_SUCCESS = 'PORTFOLIO_TYPE_SUCCESS';
export const PORTFOLIO_TYPE_FAILURE = 'PORTFOLIO_TYPE_FAILURE';


export const MOVE_GOAL_LOADING = 'MOVE_GOAL_LOADING';
export const MOVE_GOAL_SUCCESS = 'MOVE_GOAL_SUCCESS';
export const MOVE_GOAL_FAILURE = 'MOVE_GOAL_FAILURE';

// Constant for post mandate auth
export const MANDATE_AUTH_LOADING = 'MANDATE_AUTH_LOADING';
export const MANDATE_AUTH_SUCCESS = 'MANDATE_AUTH_SUCCESS';
export const MANDATE_AUTH_FAILURE = 'MANDATE_AUTH_FAILURE';

export const SELL_VERIFYOTP_LOADING = 'SELL_VERIFYOTP_LOADING';
export const SELL_VERIFYOTP_SUCCESS = 'SELL_VERIFYOTP_SUCCESS';
export const SELL_VERIFYOTP_FAILURE = 'SELL_VERIFYOTP_FAILURE';

export const SELL_RESENDOTP_LOADING = 'SELL_RESENDOTP_LOADING';
export const SELL_RESENDOTP_SUCCESS = 'SELL_RESENDOTP_SUCCESS';
export const SELL_RESENDOTP_FAILURE = 'SELL_RESENDOTP_FAILURE';

export const GOLDSILVER_LOCKER_LOADING = 'GOLDSILVER_LOCKER_LOADING';
export const GOLDSILVER_LOCKER_SUCCESS = 'GOLDSILVER_LOCKER_SUCCESS';
export const GOLDSILVER_LOCKER_FAILURE = 'GOLDSILVER_LOCKER_FAILURE';
export const STATE_NAME_LOADING = 'STATE_NAME_LOADING';
export const STATE_NAME_SUCCESS = 'STATE_NAME_SUCCESS';
export const STATE_NAME_FAILURE = 'STATE_NAME_FAILURE';
// get insurance details
export const GET_INSURANCE_DETAILS_LOADING = 'GET_INSURANCE_DETAILS_LOADING';
export const GET_INSURANCE_DETAILS_SUCCESS = 'GET_INSURANCE_DETAILS_SUCCESS';
export const GET_INSURANCE_DETAILS_FAILURE = 'GET_INSURANCE_DETAILS_FAILURE';

export const SMALLCASE_MOVEGOAL_LOADING = 'SMALLCASE_MOVEGOAL_LOADING';
export const SMALLCASE_MOVEGOAL_SUCCESS = 'SMALLCASE_MOVEGOAL_SUCCESS';
export const SMALLCASE_MOVEGOAL_FAILURE = 'SMALLCASE_MOVEGOAL_FAILURE';

export const GET_REFFERALHISTORY_LOADING = 'GET_REFFERALHISTORY_LOADING';
export const GET_REFFERALHISTORY_SUCCESS = 'GET_REFFERALHISTORY_SUCCESS';
export const GET_REFFERALHISTORY_FAILURE = 'GET_REFFERALHISTORY_FAILURE';

export const MOVEALL_ASSETS_LOADING = 'MOVEALL_ASSETS_LOADING';
export const MOVEALL_ASSETS_SUCCESS = 'MOVEALL_ASSETS_SUCCESS';
export const MOVEALL_ASSETS_FAILURE = 'MOVEALL_ASSETS_FAILURE';



export const SAVE_DATA = 'SAVE_DATA';
export const REGISTER_DATA = 'REGISTER_DATA';





export const SELL_OTP_LOADING = 'SELL_OTP_LOADING';
export const SELL_OTP_SUCCESS = 'SELL_OTP_SUCCESS';
export const SELL_OTP_FAILURE = 'SELL_OTP_FAILURE';

export const GOLDSILVER_RESENDOTP_LOADING = 'GOLDSILVER_RESENDOTP_LOADING';
export const GOLDSILVER_RESENDOTP_SUCCESS = 'GOLDSILVER_RESENDOTP_SUCCESS';
export const GOLDSILVER_RESENDOTP_FAILURE = 'GOLDSILVER_RESENDOTP_FAILURE';

export const GIFT_VERIFYOTP_LOADING = 'GIFT_VERIFYOTP_LOADING';
export const GIFT_VERIFYOTP_SUCCESS = 'GIFT_VERIFYOTP_SUCCESS';
export const GIFT_VERIFYOTP_FAILURE = 'GIFT_VERIFYOTP_FAILURE';

export const MFSELL_VERIFYOTP_LOADING = 'MFSELL_VERIFYOTP_LOADING';
export const MFSELL_VERIFYOTP_SUCCESS = 'MFSELL_VERIFYOTP_SUCCESS';
export const MFSELL_VERIFYOTP_FAILURE = 'MFSELL_VERIFYOTP_FAILURE';

export const MFSELL_RESENDOTP_LOADING = 'MFSELL_RESENDOTP_LOADING';
export const MFSELL_RESENDOTP_SUCCESS = 'MFSELL_RESENDOTP_SUCCESS';
export const MFSELL_RESENDOTP_FAILURE = 'MFSELL_RESENDOTP_FAILURE';

export const SAVE_PANDETAILS_LOADING = 'SAVE_PANDETAILS_LOADING';
export const SAVE_PANDETAILS_SUCCESS = 'SAVE_PANDETAILS_SUCCESS';
export const SAVE_PANDETAILS_FAILURE = 'SAVE_PANDETAILS_FAILURE';

export const GOLDSILVER_PAYMENTFAILED_LOADING = ' GOLDSILVER_PAYMENTFAILED_LOADING';
export const GOLDSILVER_PAYMENTFAILED_SUCCESS = 'GOLDSILVER_PAYMENTFAILED_SUCCESS';
export const GOLDSILVER_PAYMENTFAILED_FAILURE = 'GOLDSILVER_PAYMENTFAILED_FAILURE';

export const KYCSTATUS = 'KYCSTATUS';
export const KYC_REVIEW = 'KYC_REVIEW';

export const REVIEW_DATA_SUCCESS = 'REVIEW_DATA_SUCCESS';

export const MF_SETTLEMENT_LOADING = 'MF_SETTLEMENT_LOADING';
export const MF_SETTLEMENT_SUCCESS = 'MF_SETTLEMENT_SUCCESS';
export const MF_SETTLEMENT_FAILURE = 'MF_SETTLEMENT_FAILURE';

export const COMMON_BANK_ADDED_LOADING = 'COMMON_BANK_ADDED_LOADING';
export const COMMON_BANK_ADDED_SUCCESS = 'COMMON_BANK_ADDED_SUCCESS';
export const COMMON_BANK_ADDED_FAILURE = 'COMMON_BANK_ADDED_FAILURE';


export const GET_MFBANK_LOADING = 'GET_MFBANK_LOADING';
export const GET_MFBANK_SUCCESS = 'GET_MFBANK_SUCCESS';
export const GET_MFBANK_FAILURE = 'GET_MFBANK_FAILURE';

export const URL_REDUCER = 'URL_REDUCER';
export const SAVE_KYC_ESIGNDATA_LOADING = 'SAVE_KYC_ESIGNDATA_LOADING';
export const SAVE_KYC_ESIGNDATA_SUCCESS = 'SAVE_KYC_ESIGNDATA_SUCCESS';
export const SAVE_KYC_ESIGNDATA_FAILURE = 'SAVE_KYC_ESIGNDATA_FAILURE';


export const SKIP_DASHBOARD_LOADING = 'SKIP_DASHBOARD_LOADING';
export const SKIP_DASHBOARD_SUCCESS = 'SKIP_DASHBOARD_SUCCESS';
export const SKIP_DASHBOARD_FAILURE = 'SKIP_DASHBOARD_FAILURE';




export const GET_COMPANY_LIST_LOADING = 'GET_COMPANY_LIST_LOADING';
export const GET_COMPANY_LIST_SUCCESS = 'GET_COMPANY_LIST_SUCCESS';
export const GET_COMPANY_LIST_FAILURE = 'GET_COMPANY_LIST_FAILURE';

export const ADD_POLICY_LOADING = 'ADD_POLICY_LOADING';
export const ADD_POLICY_SUCCESS = 'ADD_POLICY_SUCCESS';
export const ADD_POLICY_FAILURE = 'ADD_POLICY_FAILURE';
export const GET_DASHBOARDCARD_LOADING = 'GET_DASHBOARDCARD_LOADING';
export const GET_DASHBOARDCARD_SUCCESS = 'GET_DASHBOARDCARD_SUCCESS';
export const GET_DASHBOARDCARD_FAILURE = 'GET_DASHBOARDCARD_FAILURE';

export const FD_HISTORY_SUCCESS = 'FD_HISTORY_SUCCESS';
export const FD_USER_DATA_SUCCESS = 'FD_USER_DATA_SUCCESS';

export const GET_SIGN_LOADING = 'GET_SIGN_LOADING';
export const GET_SIGN_SUCCESS = 'GET_SIGN_SUCCESS';
export const GET_SIGN_FAILURE = 'GET_SIGN_FAILURE';

export const UPLOAD_SIGN_LOADING = 'UPLOAD_SIGN_LOADING';
export const UPLOAD_SIGN_SUCCESS = 'UPLOAD_SIGN_SUCCESS';
export const UPLOAD_SIGN_FAILURE = 'UPLOAD_SIGN_FAILURE';

export const GET_MFSIP_LISTING_LOADING = 'GET_MFSIP_LISTING_LOADING';
export const GET_MFSIP_LISTING_SUCCESS = 'GET_MFSIP_LISTING_SUCCESS';
export const GET_MFSIP_LISTING_FAILURE = 'GET_MFSIP_LISTING_FAILURE';

//list category item
export const GET_ALL_CATEGORYLIST_LOADING = 'GET_ALL_CATEGORYLIST_LOADING';
export const GET_ALL_CATEGORYLIST_SUCCESS = 'GET_ALL_CATEGORYLIST_SUCCESS';
export const GET_ALL_CATEGORYLIST_FAILURE = 'GET_ALL_CATEGORYLIST_FAILURE';


export const UPDATE_CART_FLAVOUR_LOADING = 'UPDATE_CART_FLAVOUR_LOADING';
export const UPDATE_CART_FLAVOUR_SUCCESS = 'UPDATE_CART_FLAVOUR_SUCCESS';
export const UPDATE_CART_FLAVOUR_FAILURE = 'UPDATE_CART_FLAVOUR_FAILURE';

export const UPDATE_EVALUATION_LOADING = 'UPDATE_EVALUATION_LOADING';
export const UPDATE_EVALUATION_SUCCESS = 'UPDATE_EVALUATION_SUCCESS';
export const UPDATE_EVALUATION_FAILURE = 'UPDATE_EVALUATION_FAILURE';



export const ADD_ENQUIRY_LOADING = 'ADD_ENQUIRY_LOADING';
export const ADD_ENQUIRY_SUCCESS = 'ADD_ENQUIRY_SUCCESS';
export const ADD_ENQUIRY_FAILURE = 'ADD_ENQUIRY_FAILURE';


export const ADD_FOLLOWUP_LOADING = 'ADD_FOLLOWUP_LOADING';
export const ADD_FOLLOWUP_SUCCESS = 'ADD_FOLLOWUP_SUCCESS';
export const ADD_FOLLOWUP_FAILURE = 'ADD_FOLLOWUP_FAILURE';


export const ADD_BOOKING_LOADING = 'ADD_BOOKING_LOADING';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAILURE = 'ADD_BOOKING_FAILURE';


export const GET_FOLLOWUP_DETAILS_LOADING = 'GET_FOLLOWUP_DETAILS_LOADING';
export const GET_FOLLOWUP_DETAILS_SUCCESS = 'GET_FOLLOWUP_DETAILS_SUCCESS';
export const GET_FOLLOWUP_DETAILS_FAILURE = 'GET_FOLLOWUP_DETAILS_FAILURE';

export const GET_ENQUIRY_DETAILS_LOADING = 'GET_ENQUIRY_DETAILS_LOADING';
export const GET_ENQUIRY_DETAILS_SUCCESS = 'GET_ENQUIRY_DETAILS_SUCCESS';
export const GET_ENQUIRY_DETAILS_FAILURE = 'GET_ENQUIRY_DETAILS_FAILURE';

export const UPDATE_ENQUIRY_LOADING = 'UPDATE_ENQUIRY_LOADING';
export const UPDATE_ENQUIRY_SUCCESS = 'UPDATE_ENQUIRY_SUCCESS';
export const UPDATE_ENQUIRY_FAILURE = 'UPDATE_ENQUIRY_FAILURE';


export const UPDATE_PROFILEPIC_LOADING = 'UPDATE_PROFILEPIC_LOADING';
export const UPDATE_PROFILEPIC_SUCCESS = 'UPDATE_PROFILEPIC_SUCCESS';
export const UPDATE_PROFILEPIC_FAILURE = 'UPDATE_PROFILEPIC_FAILURE';


export const GET_CARDATA_LOADING = 'GET_CARDATA_LOADING';
export const GET_CARDATA_SUCCESS = 'GET_CARDATA_SUCCESS';
export const GET_CARDATA_FAILURE = 'GET_CARDATA_FAILURE';


export const GET_COLOR_LIST_LOADING = 'GET_COLOR_LIST_LOADING';
export const GET_COLOR_LIST_SUCCESS = 'GET_COLOR_LIST_SUCCESS';
export const GET_COLOR_LIST_FAILURE = 'GET_COLOR_LIST_FAILURE';


export const UPDATE_SRM_ENQUIRY_LOADING = 'UPDATE_SRM_ENQUIRY_LOADING';
export const UPDATE_SRM_ENQUIRY_SUCCESS = 'UPDATE_SRM_ENQUIRY_SUCCESS';
export const UPDATE_SRM_ENQUIRY_FAILURE = 'UPDATE_SRM_ENQUIRY_FAILURE';

export const GET_MYTEAMS_DETAILS_LOADING = 'GET_MYTEAMS_DETAILS_LOADING';
export const GET_MYTEAMS_DETAILS_SUCCESS = 'GET_MYTEAMS_DETAILS_SUCCESS';
export const GET_MYTEAMS_DETAILS_FAILURE = 'GET_MYTEAMS_DETAILS_FAILURE';


export const ADD_ASSIGN_ENQUIRY_LOADING = 'ADD_ASSIGN_ENQUIRY_LOADING';
export const ADD_ASSIGN_ENQUIRY_SUCCESS = 'ADD_ASSIGN_ENQUIRY_SUCCESS';
export const ADD_ASSIGN_ENQUIRY_FAILURE = 'ADD_ASSIGN_ENQUIRY_FAILURE';

export const GET_RM_DETAILS_LOADING = 'GET_RM_DETAILS_LOADING';
export const GET_RM_DETAILS_SUCCESS = 'GET_RM_DETAILS_SUCCESS';
export const GET_RM_DETAILS_FAILURE = 'GET_RM_DETAILS_FAILURE';



export const REFERRAL_CODE = 'REFERRAL_CODE';

export const GET_EXPENSE_LISTING = 'GET_EXPENSE_LISTING'

// for plan goal wealth

export const GET_PLAN_GOALWEALTH_LIST = 'GET_PLAN_GOALWEALTH_LIST'
export const GET_ASSETS_DATA_LIST = 'GET_ASSETS_DATA_LIST'
export const GET_GOALBASE_GROUP_LIST = 'GET_GOALBASE_GROUP_LIST'
export const GET_GOALBASE_DETAILS = 'GET_GOALBASE_DETAILS'
export const GET_SCHEME_DETAILS = 'GET_SCHEME_DETAILS'
export const GET_FUND_TXN_HISTORY_LIST = 'GET_FUND_TXN_HISTORY_LIST'
export const GET_FINANCIAL_GOALWEALTH_LIST = 'GET_FINANCIAL_GOALWEALTH_LIST'


// FOR MF

export const AMC_LISTING = 'AMC_LISTING'
export const CATEGORY_LISTING = 'CATEGORY_LISTING'
export const AMC_COUNT = 'AMC_COUNT'

export const GET_BILL_CAT_SUCCESS = 'GET_BILL_CAT_SUCCESS';
export const GET_FAV_BILLER_SUCCESS = 'GET_FAV_BILLER_SUCCESS';
export const GET_BILLER_TXN_HISTORY = 'GET_BILLER_TXN_HISTORY';
export const GET_BILLER_TXN_HISTORY_LTD = 'GET_BILLER_TXN_HISTORY_LTD';

export const RETIRE_CALC = 'RETIRE_CALC';
export const GET_SIPLIST = 'GET_SIPLIST';
export const GET_SIPBANKLIST = 'GET_SIPBANKLIST';

export const MF_INVESTED_AMOUNT = 'MF_INVESTED_AMOUNT'
export const MF_LIST = 'MF_LIST'
export const MF_LIST_COUNT = 'MF_LIST_COUNT'


export const GET_MF_GROUP_LIST = 'GET_MF_GROUP_LIST'
export const GET_STOCKS_GROUP_LIST = 'GET_STOCKS_GROUP_LIST'
export const GET_GOLD_GROUP_LIST = 'GET_GOLD_GROUP_LIST'
export const GET_FD_GROUP_LIST = 'GET_FD_GROUP_LIST'
export const GET_NPS_GROUP_LIST = 'GET_NPS_GROUP_LIST'

export const WEALTH_UPDATED = 'WEALTH_UPDATED';
export const KYC_STATUS = 'KYC_STATUS';
export const REG_DATA = 'REG_DATA';
export const HOLDINGS_DATA = 'HOLDINGS_DATA';


