import { StyleSheet, Dimensions, Platform } from 'react-native';
import {
  widthPercentageToDP,
  heightPercentageToDP,
  normalizeHeight,
  normalizeWidth,
} from '../components/ResponsiveScreen';
import Global from '../global';
const { height, width } = Dimensions.get('screen');

const GlobalStyles = StyleSheet.create({
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spaceBetweenCenter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mainsection: {
    flex: 1,
   // height: '100%',
  },
  
  offwhitesection: {
    backgroundColor: Global.color.oppwhite,
  },
  primarysection: {
    backgroundColor: Global.color.white,
  },

  outerBlock: {
    paddingTop: normalizeHeight(16)
  },

  innerBlock: {
    paddingHorizontal: normalizeWidth(16)
  },

  dropDownIos: {
    zIndex: Platform.OS === 'ios' ? 100 : 0,
  },
  roundedBox: {
    flexDirection: 'row',
    marginTop: heightPercentageToDP('3.59%'),
    justifyContent: 'space-between',
  },
  box: {
    borderWidth: 0.5,
    borderColor: Global.color.white25070,
    borderRadius: 15,
  },
  roundedText: {
    color: Global.color.white25070,
    fontFamily: Global.font.font_family_fr,
    fontSize: heightPercentageToDP('1.55%'),
    lineHeight: heightPercentageToDP('3%'),
    width: widthPercentageToDP('28%'),
    alignItems: 'center',
    textAlign: 'center',
    alignSelf: 'center',
  },
  faqheader: {
    fontFamily: Global.font.font_family_fb,
    fontSize: normalizeHeight(15),
    textAlign: 'center',
    letterSpacing: 1,
    color: Global.color.white25090,
    marginTop: normalizeHeight(5),
  },
  maintext :{
  fontSize: normalizeHeight(28),
  lineHeight: normalizeHeight(31),
  fontFamily: Global.font.TextMedium,
  fontWeight: '500',
  letterSpacing: 0,
  color:Global.color.white,
  paddingTop:normalizeHeight(12)
  },

  mainContainer: {
    backgroundColor: Global.color.oppwhite,
    paddingHorizontal: widthPercentageToDP('4%'),
    height: '100%',
  },
  innerContainer: {
    paddingHorizontal: widthPercentageToDP('4%'),
    paddingVertical: heightPercentageToDP('2.12%'),
  },
  innerContainerDashboard: {
    paddingTop: heightPercentageToDP('2.12%'),
    paddingHorizontal: normalizeWidth(15),
  },
  datacontainerWithoutF: {
    paddingHorizontal: normalizeWidth(15),
    height: '100%',
    backgroundColor: Global.color.primary,
  },
  datacontainerwhiteWithoutF: {
    paddingHorizontal: normalizeWidth(15),
    height: '100%',
    backgroundColor: Global.color.oppwhite,
  },
  fieldspacing: {
    paddingHorizontal: normalizeWidth(15),
  },
  errorstyle: {
    color: Global.color.errorRed,
    textAlign: 'right',
    fontFamily: Global.font.font_family_fr,
    fontWeight: '400',
    fontSize: normalizeHeight(12),
    zIndex: 2,
  },
  rounderbutton: {
    flex: 0,
    backgroundColor: Global.color.primary,
    height: normalizeHeight(50),
    width: '100%',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: normalizeHeight(100),
    marginBottom: 0,
  },

  transpbutton: {
    flex: 0,
    backgroundColor: 'rgba(41, 58, 100, 0.5)',
    height: normalizeHeight(50),
    width: '100%',
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: normalizeHeight(100),
    marginBottom: 0,
  },
  inputboxfull: {
    height: normalizeHeight(35),
    borderWidth: 2,
    backgroundColor: Global.color.white,
    borderColor: Global.color.borderColor,
    borderRadius: 5,
    padding: 1,
    paddingLeft: normalizeWidth(10),
    marginTop: normalizeHeight(5),
  },
  label: {
    color: Global.color.black,
    fontSize: normalizeHeight(14),
    fontFamily: Global.font.font_family_fb,
    fontWeight: '400',
  },
  // label: {
  //   fontSize: heightPercentageToDP('1.98%'),
  //   lineHeight: heightPercentageToDP('2.83%'),
  //   fontFamily: Global.font.font_family_fr,
  //   color: Global.color.faintBlack,
  // },
  submitButtonText: {
    color: Global.color.white,
    fontSize: normalizeHeight(16),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.1,
  },

  // lblwhite14: {
  //   fontSize: heightPercentageToDP('2.27%'),
  //   letterSpacing: 0.1,
  //   color: Global.color.white,

  //   lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  // },
  // lblprimary14: {
  //   fontSize: heightPercentageToDP('2.27%'),
  //   letterSpacing: 0.1,
  //   color: Global.color.primary,
  //   // TextTransform: 'uppercase',
  //   textTransform: 'capitalize',
  //   lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  // },
  lblwhite16: {
    fontSize: heightPercentageToDP('2.27%'),
    color: Global.color.white,
    lineHeight: heightPercentageToDP('3.54%'),
    fontFamily: Global.font.font_family_fr,
  },
  // lblblue16b: {
  //   fontSize: heightPercentageToDP('2.24%'),
  //   color: Global.color.primary,
  //   lineHeight: heightPercentageToDP('3.54%'),
  //   letterSpacing: 0.8,
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  // },
  lblwhite16b: {
    fontSize: normalizeHeight(16),
    color: Global.color.white,
    fontFamily: Global.font.font_family_fb,
    fontWeight: '700',
  },
  line: {
    backgroundColor: '#242A34',
    height: normalizeHeight(1),
    width: '100%'
  },

  // lblwhite15b: {
  //   fontSize: heightPercentageToDP('2.40%'),
  //   color: 'rgba(250, 250, 250, 0.25)',
  //   lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  // },
  // buttonEnable: {
  //   fontSize: heightPercentageToDP('2.27%'),
  //   color: Global.color.lightgrey,
  //   // lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  //   letterSpacing: 0.3,
  // },
  // lblgrey15b: {
  //   fontSize: heightPercentageToDP('2.40%'),
  //   color: Global.color.lightgrey,
  //   lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  // },

  // lblgreydis15b: {
  //   fontSize: heightPercentageToDP('2.40%'),
  //   color: Global.color.white25,
  //   lineHeight: heightPercentageToDP('3.54%'),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  // },

  // lbl14: {
  //   fontSize: normalizeHeight(14),
  //   lineHeight: normalizeHeight(20),
  //   fontFamily: Global.font.font_family_fr,
  // },
  // lbl20: {
  //   fontSize: normalizeHeight(20),
  //   lineHeight: normalizeHeight(25),
  //   fontFamily: Global.font.font_family_fr,
  // },
  // lbl17: {
  //   fontSize: normalizeHeight(17),
  //   lineHeight: normalizeHeight(25),
  //   fontFamily: Global.font.font_family_fr,
  // },
  // lblwhite18b: {
  //   fontFamily: Global.font.font_family_fr,
  //   color: Global.color.primary,
  //   fontSize: heightPercentageToDP('1.98%'),
  //   lineHeight: heightPercentageToDP('2.41%'),
  //   letterSpacing: 0.1,
  //   textTransform: 'capitalize',
  // },
  // lbl16primary: {
  //   fontFamily: Global.font.font_family_fb,
  //   fontSize: normalizeHeight(16),
  //   lineHeight: normalizeHeight(16),
  //   color: Global.color.primary,
  // },
  // lbl16primaryb: {
  //   fontFamily: Global.font.font_family_fb,
  //   fontSize: normalizeHeight(16),
  //   lineHeight: normalizeHeight(20),
  //   letterSpacing: 0.1,
  //   color: Global.color.primary,
  // },
  // lbl14primaryb: {
  //   fontFamily: Global.font.font_family_fb,
  //   fontSize: normalizeHeight(14),
  //   lineHeight: normalizeHeight(20),
  //   letterSpacing: 0.1,
  //   color: Global.color.primary,
  // },
  // lbl12primary: {
  //   fontFamily: Global.font.font_family_fr,
  //   fontSize: heightPercentageToDP('1.7%'),
  //   color: Global.color.primary,
  // },

  // lblyellow20b: {
  //   fontFamily: Global.font.font_family_fb,
  //   fontSize: heightPercentageToDP('2.27%'),
  //   lineHeight: heightPercentageToDP('2.69%'),
  //   letterSpacing: 0.1,
  //   color: Global.color.primary,
  // },
  // swipablecont: {
  //   // Flex: 1,
  //   marginTop: normalizeHeight(23),
  //   backgroundColor: Global.color.oppwhite,
  //   borderTopRightRadius: 20,
  //   borderTopLeftRadius: 20,
  //   height: Global.structure.screenHeight,
  // },
  // swipableconthidden: {
  //   // Flex: 1,
  //   marginTop: normalizeHeight(23),
  //   backgroundColor: Global.color.oppwhite,
  //   borderTopRightRadius: 20,
  //   borderTopLeftRadius: 20,
  //   // Height: Global.structure.screenHeight,
  // },
  norecordfound: {
    color: Global.color.darkgrey,
    fontSize: normalizeHeight(20),
    marginBottom: normalizeHeight(20),
    marginTop: '30%',
    alignItems: 'center',
    textAlign: 'center',
    letterSpacing: 1,
    lineHeight: normalizeHeight(30),
    fontFamily: Global.font.font_family_fr,
  },
  internetstyle: {
    backgroundColor: Global.color.black,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  internetText: {
    fontSize: heightPercentageToDP('2.12%'),
    lineHeight: heightPercentageToDP('2.55%'),
    textAlign: 'center',
    marginTop: heightPercentageToDP('2.12%'),
    marginBottom: heightPercentageToDP('2.12%'),
    color: Global.color.white,
  },
  // sliderpanel: {
  //   flex: 1,
  //   backgroundColor: Global.color.oppwhite,
  //   borderTopRightRadius: 20,
  //   borderTopLeftRadius: 20,
  // },
  // mutualfundspanel: {
  //   flex: 1,
  //   backgroundColor: '#354876',
  //   borderTopRightRadius: 20,
  //   borderTopLeftRadius: 20,
  // },
  // sliderpanelHeader: {
  //   backgroundColor: Global.color.oppwhite,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   padding: heightPercentageToDP('0.71%'),
  //   marginLeft: widthPercentageToDP('4%'),
  //   marginRight: widthPercentageToDP('4%'),
  //   marginTop: heightPercentageToDP('0.25%'),
  // },
  bar: {
    width: widthPercentageToDP('13.33%'),
    height: 2,
    borderRadius: 2,
    marginTop: heightPercentageToDP('0.61%'),
    marginBottom: heightPercentageToDP('0.71%'),
    backgroundColor: 'rgba(250, 250, 250, 0.25)',
  },
  bar1: {
    width: '15%',
    height: heightPercentageToDP('0.71%'),
    borderRadius: heightPercentageToDP('0.71%'),
    marginTop: heightPercentageToDP('0.71%'),
    marginBottom: heightPercentageToDP('0.71%'),
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
  },
  slidercontainer: {
    // Flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: widthPercentageToDP('4%'),
  },
  addexpense: {
    position: 'absolute',
    right: widthPercentageToDP('5%'),
    bottom: heightPercentageToDP('5.81%'),
    borderRadius: heightPercentageToDP('7.08%'),
    backgroundColor: Global.color.gradientblue,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: Global.color.gradientblue,
    elevation: heightPercentageToDP('0.71%'),
    width: widthPercentageToDP('16%'),
    height: widthPercentageToDP('16%'),
  },
  // expenseicon: {
  //   padding: heightPercentageToDP('1.42%'),
  //   color: Global.color.primary,
  //   fontSize: heightPercentageToDP('5.67%'),
  // },
  contentPara: {
    fontSize: normalizeHeight(12),
    fontFamily: Global.font.font_family_fr,
    lineHeight: heightPercentageToDP('1.98%'),
    letterSpacing: 0.1,
    textAlign: 'justify',
  },
  contentGap: {
    marginBottom: heightPercentageToDP('3%'),
    fontFamily: Global.font.font_family_fb,
  },
  // contentSmallGap: {
  //   marginBottom: heightPercentageToDP('1%'),
  // },
  contentBold: {
    fontSize: heightPercentageToDP('1.41%'),
    fontFamily: Global.font.font_family_fb,
    lineHeight: heightPercentageToDP('1.98%'),
    fontWeight: '500',
  },
  // norecordsblock: {
  //   flex: 1,
  //   height: heightPercentageToDP('96.6%'),
  //   alignItems: 'center',
  //   justifyContent: 'center',
  // },
  // norecordstext: {
  //   fontSize: heightPercentageToDP('2.2%'),
  //   lineHeight: heightPercentageToDP('3.68%'),
  //   color: Global.color.primary,
  //   textAlign: 'center',
  // },

  centeralignnotifiselected: {
    alignSelf: 'center',
    marginTop: -10,
    paddingLeft: widthPercentageToDP('4%'),
    color: Global.color.faintBlack,
    lineHeight: 16,
    fontSize: 12,
    fontFamily: Global.font.font_family_fr,
  },
  textwithroundcheck: {
    marginTop: -5,
    paddingLeft: widthPercentageToDP('4%'),
    color: Global.color.primary,
    lineHeight: normalizeHeight(16),
    fontSize: normalizeHeight(12),
    fontFamily: Global.font.font_family_fr,
  },
  textwithouttopcheck: {
    paddingLeft: widthPercentageToDP('4%'),
    color: Global.color.primary,
    lineHeight: normalizeHeight(16),
    fontSize: normalizeHeight(12),
    fontFamily: Global.font.font_family_fr,
  },

  radiobuttonround: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: widthPercentageToDP('2%'),
    paddingTop: widthPercentageToDP('5%'),
    color: Global.color.faintBlackrgb,
  },

  // successmodalmainview: {
  //   backgroundColor: Global.color.white,
  //   position: 'absolute',
  //   bottom: heightPercentageToDP('14.16'),
  //   zIndex: 1,
  //   padding: heightPercentageToDP('1.41%'),
  //   width: '70%',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   alignSelf: 'center',
  //   alignContent: 'center',
  //   textAlign: 'center',
  // },
  successmodaltext: {
    color: Global.color.white25070,
    fontFamily: Global.font.font_family_fr,
    textAlign: 'center',
    fontSize: heightPercentageToDP('2.12%'),
    lineHeight: heightPercentageToDP('2.83%'),
    letterSpacing: 0.3,
    fontWeight: '300',
  },
  bankLabel: {
    color: Global.color.white25070,
    fontFamily: Global.font.font_family_fr,
    fontSize: heightPercentageToDP('1.84%'),
    lineHeight: heightPercentageToDP('2.26%'),
    letterSpacing: 0.3,
    fontWeight: '400',
  },
  bankValue: {
    color: Global.color.white25090,
    fontFamily: Global.font.font_family_fr,
    fontSize: heightPercentageToDP('1.84%'),
    lineHeight: heightPercentageToDP('2.26%'),
    letterSpacing: 0.3,
    fontWeight: '400',
  },
  eMandateText: {
    fontSize: heightPercentageToDP('2.40%'),
    lineHeight: heightPercentageToDP('2.83%'),
    color: Global.color.white25070,
    fontFamily: Global.font.font_family_fb,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  successmodalimage: {
    width: heightPercentageToDP('4.24%'),
    height: heightPercentageToDP('4.24%'),
  },
  // fieldView: {
  //   marginTop: 0,
  // },
  labelText: {
    fontFamily: Global.font.font_family_fr,
    fontSize: normalizeHeight(14),
    color: Global.color.black,
    fontWeight:'bold'
  },
  labelText1: {
    fontFamily: Global.font.semiBold,
    fontSize: normalizeHeight(16),
    color: Global.color.white,
  },
  labelTextz: {
    fontFamily: Global.font.TextMedium,
            fontSize: normalizeHeight(18),
            lineHeight:normalizeHeight(21),
            color: Global.color.blackz,
  },
  label2:
  {
    color: Global.color.error, fontFamily: Global.font.font_family_fr
  },
  setmargin: {
    marginTop: normalizeHeight(5),
  },
  setselectBox: {
    marginVertical: 20,
    marginHorizontal: normalizeWidth(15),
  },
  // noteTextgold: {
  //   fontFamily: Global.font.font_family_fr,
  //   fontSize: heightPercentageToDP('1.55%'),
  //   lineHeight: heightPercentageToDP('2.12%'),
  //   letterSpacing: 0.1,
  //   color: Global.color.green,
  //   marginLeft: normalizeWidth(10),
  //   marginTop: normalizeHeight(10),
  // },
  container: {
    backgroundColor: Global.color.primary,
    flex: 1,
  },
  headerView: {
    flexDirection: 'row',
    marginHorizontal: normalizeWidth(15),
    marginVertical: normalizeHeight(17),
    justifyContent: 'space-between',
  },
  // menuImage: {
  //   height: normalizeHeight(30),
  //   width: normalizeWidth(30),
  // },
  backIcon: {
    height: normalizeHeight(30),
    width: normalizeWidth(30),
  },
  iconView: {
    height: normalizeHeight(20),
    width: normalizeWidth(20),
  },
  searchImage: {
    height: normalizeHeight(16),
    width: normalizeWidth(16),
  },
  filterimage: {
    height: normalizeHeight(15),
    width: normalizeWidth(15),
    marginLeft: normalizeWidth(5),
  },
  linepieicon: {
    height: normalizeHeight(20),
    width: normalizeWidth(28),
  },

  // infoClose: {
  //   height: normalizeHeight(20),
  //   width: normalizeWidth(28),
  // },
  swapimage: {
    height: normalizeHeight(17),
    width: normalizeWidth(17),
  },
  infoimage: {
    height: normalizeHeight(16),
    width: normalizeWidth(16),
  },
  // locationImage: {
  //   height: normalizeHeight(18),
  //   width: normalizeWidth(22),
  // },
  // bellImage: {
  //   height: normalizeHeight(25),
  //   width: normalizeWidth(25),
  // },
  headerText: {
    fontSize: normalizeHeight(19),
    color: Global.color.lightgrey,
    lineHeight: normalizeHeight(23),
    fontFamily: Global.font.font_family_fb,
  },
  // catalogHead: {
  //   fontSize: normalizeHeight(17),
  //   color: Global.color.lightgrey,
  //   lineHeight: normalizeHeight(20),
  //   fontFamily: Global.font.font_family_fb,
  // },
  titleView: {
    marginHorizontal: normalizeWidth(15),
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: normalizeHeight(20),
    alignItems: 'center',
  },
  // locationView: {
  //   height: normalizeHeight(35),
  //   width: '50%',
  //   backgroundColor: Global.color.navyblueColor,
  //   borderRadius: normalizeHeight(10),
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   paddingHorizontal: normalizeWidth(5),
  // },
  // textlocation: {
  //   color: Global.color.lightgrey + 50,
  //   fontSize: normalizeHeight(13),
  //   fontFamily: Global.font.font_family_fr,
  //   marginLeft: normalizeWidth(5),
  //   lineHeight: normalizeHeight(15),
  //   textAlign: 'left',
  // },
  searchView: {
    height: normalizeHeight(35),
    marginHorizontal: normalizeHeight(15),
    backgroundColor: Global.color.darkblue2Color,
    borderRadius: normalizeHeight(10),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchViewdeals: {
    height: normalizeHeight(48),
    marginHorizontal: normalizeWidth(15),
    paddingHorizontal: normalizeWidth(15),
    backgroundColor: Global.color.mirage,
    borderRadius: normalizeHeight(50),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    height: normalizeHeight(35),
    marginTop: normalizeHeight(4),
    width: '90%',
    paddingHorizontal: normalizeWidth(10),
    color: Global.color.white,
    fontFamily: Global.font.font_family_fr,
  },

  inputCircle: {
    height: normalizeHeight(48),
    width: '90%',
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(18),
    color: Global.color.white,
    fontFamily: Global.font.font_family_fr,
  },
  // filertView: {
  //   marginTop: 20,
  //   paddingHorizontal: 15,
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'space-between',
  // },
  texts: {
    color: Global.color.lightgrey,
    fontSize: normalizeHeight(13),
    fontFamily: Global.font.font_family_fr,
    lineHeight: normalizeHeight(16),
  },
  filterTexts: {
    color: Global.color.white25070,
    fontSize: normalizeHeight(13),
    fontFamily: Global.font.font_family_fr,
    lineHeight: normalizeHeight(15),
    fontWeight: '400',
    letterSpacing: 0.3,
  },
  selectCategoryText: {
    color: Global.color.cyanblue,
    fontSize: normalizeHeight(11),
    fontFamily: Global.font.font_family_fr,
    lineHeight: normalizeHeight(16),
  },
  nearbyflexView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomView: {
    marginTop: 10,
    paddingHorizontal: 20,
    borderColor: Global.color.white50,
    borderBottomWidth: 1,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#00000050',
  },
  // allDataView: {
  //   paddingHorizontal: 15,
  //   alignItems: 'flex-start',
  //   justifyContent: 'center',
  // },
  modalView: {
    backgroundColor: Global.color.primary,
    borderRadius: 20,
    shadowColor: Global.color.cyanblue,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: width - 40,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  // buttonOpen: {
  //   backgroundColor: '#F194FF',
  // },
  // buttonClose: {
  //   backgroundColor: '#2196F3',
  // },
  textStyle: {
    color: 'white',
    fontWeight: '600',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  horizontalLine: {
    marginTop: 20,
    borderBottomColor: 'rgba(250, 250, 250, 0.1)',
    borderBottomWidth: 0.5,
    marginHorizontal: 0,
  },
  // maxPrice: {
  //   textAlign: 'center',
  //   marginTop: 10,
  //   fontSize: 15,
  //   lineHeight: 18,
  //   fontFamily: Global.font.font_family_fr,
  //   color: Global.color.white,
  //   textDecorationLine: 'line-through',
  //   textDecorationStyle: 'solid',
  //   textDecorationColor: Global.color.white,
  // },
  // productPrice: {
  //   fontSize: 15,
  //   lineHeight: 18,
  //   color: Global.color.cyanblue,
  //   fontFamily: Global.font.font_family_fr,
  //   textAlign: 'center',
  //   marginTop: 10,
  // },
  subiewTitle: {
    fontSize: heightPercentageToDP('2.69%'),
    lineHeight: heightPercentageToDP('3.25%'),
    fontFamily: Global.font.font_family_fb,
    color: Global.color.lightgrey,
    letterSpacing: 0.3,
    fontWeight: '500',
  },

  // ....................New Styles........................

  // font11R: {
  //   fontSize: normalizeHeight(11),
  //   lineHeight: normalizeHeight(16),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },

  font13R: {
    fontSize: normalizeHeight(18),
    lineHeight: normalizeHeight(22),
    fontFamily: Global.font.font_family_fr,
    fontWeight: '400',
    letterSpacing: 0.3,
    paddingTop:normalizeHeight(12)
  },

  font13R1: {
    fontSize: normalizeHeight(18),
    lineHeight: normalizeHeight(22),
    fontFamily: Global.font.font_family_fb,
    fontWeight: '600',
    letterSpacing: 0.3,
    paddingTop:normalizeHeight(12)
  },

  // font15R: {
  //   fontSize: normalizeHeight(15),
  //   lineHeight: normalizeHeight(20),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },

  // font17R: {
  //   fontSize: normalizeHeight(17),
  //   lineHeight: normalizeHeight(22),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },
  // font19R: {
  //   fontSize: normalizeHeight(19),
  //   lineHeight: normalizeHeight(24),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },

  // font24R: {
  //   fontSize: normalizeHeight(24),
  //   lineHeight: normalizeHeight(30),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },
  // font30R: {
  //   fontSize: normalizeHeight(30),
  //   lineHeight: normalizeHeight(36),
  //   fontFamily: Global.font.font_family_fr,
  //   fontWeight: '400',
  //   letterSpacing: 0.3,
  // },

  // font11B: {
  //   fontSize: normalizeHeight(11),
  //   lineHeight: normalizeHeight(16),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  //   letterSpacing: 0.3,
  // },
  // font13B: {
  //   fontSize: normalizeHeight(13),
  //   lineHeight: normalizeHeight(18),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  //   letterSpacing: 0.3,
  // },
  font15B: {
    fontSize: normalizeHeight(16),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fb,
    fontWeight: '700',
   // letterSpacing: 0.3,
  },

  font15Bc: {
    fontSize: normalizeHeight(18),
    lineHeight: normalizeHeight(21),
    fontFamily: Global.font.font_family_fb,
    fontWeight: '600',
   // letterSpacing: 0.3,
  },
  font17B: {
    fontSize: normalizeHeight(17),
    lineHeight: normalizeHeight(22),
    fontFamily: Global.font.font_family_fb,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  font19B: {
    fontSize: normalizeHeight(22),
    lineHeight: normalizeHeight(27),
    fontFamily: Global.font.font_family_fr,
    fontWeight: '600',
    letterSpacing: 0.3,
  },

  font19Bc: {
    fontSize: normalizeHeight(24),
    lineHeight: normalizeHeight(29),
    fontFamily: Global.font.semiBold,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  logotitle: {
    fontSize: normalizeHeight(32),
    lineHeight: normalizeHeight(68),
    fontFamily: Global.font.bold,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  texttitle: {
    fontSize: normalizeHeight(12),
    lineHeight: normalizeHeight(16),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
  },
  texttitledes: {
    fontSize: normalizeHeight(14),
    lineHeight: normalizeHeight(17),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
  },
  // font24B: {
  //   fontSize: normalizeHeight(24),
  //   lineHeight: normalizeHeight(30),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  //   letterSpacing: 0.3,
  // },
  // font30B: {
  //   fontSize: normalizeHeight(30),
  //   lineHeight: normalizeHeight(36),
  //   fontFamily: Global.font.font_family_fb,
  //   fontWeight: '500',
  //   letterSpacing: 0.3,
  // },

  // opacity25: {
  //   opacity: 0.25,
  // },

  // opacity50: {
  //   opacity: 0.5,
  // },
  // opacity70: {
  //   opacity: 0.7,
  // },
  // opacity90: {
  //   opacity: 0.9,
  // },
  // opacity100: {
  //   opacity: 1,
  // },

  // fontfamilyregular: {
  //   fontFamily: Global.font.font_family_fr,
  // },

  // fontfamilymedium: {
  //   fontFamily: Global.font.font_family_fb,
  // },

  // borderRadius4: {
  //   borderRadius: 4,
  // },

  // borderRadius6: {
  //   borderRadius: 6,
  // },
  // borderRadius8: {
  //   borderRadius: 8,
  // },
  // borderRadius10: {
  //   borderRadius: 10,
  // },
  // borderRadius12: {
  //   borderRadius: 12,
  // },
  // borderRadius15: {
  //   borderRadius: 15,
  // },
  // borderRadius20: {
  //   borderRadius: 20,
  // },
  // borderRadius30: {
  //   borderRadius: 30,
  // },

  // size12: {
  //   height: normalizeHeight(12),
  //   width: normalizeWidth(12),
  // },

  // size18: {
  //   height: normalizeHeight(18),
  //   width: normalizeWidth(18),
  // },

  // size24: {
  //   height: normalizeHeight(24),
  //   width: normalizeWidth(24),
  // },
  // size30: {
  //   height: normalizeHeight(30),
  //   width: normalizeWidth(30),
  // },
  // size48: {
  //   height: normalizeHeight(48),
  //   width: normalizeWidth(48),
  // },
  // size100: {
  //   height: normalizeHeight(100),
  //   width: normalizeWidth(100),
  // },
  // size150: {
  //   height: normalizeHeight(150),
  //   width: normalizeWidth(150),
  // },
  // size200: {
  //   height: normalizeHeight(200),
  //   width: normalizeWidth(200),
  // },
  // size250: {
  //   height: normalizeHeight(250),
  //   width: normalizeWidth(250),
  // },

  // enablefilledbutton1: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(250),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enablefilledbutton2: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(150),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enablefilledbutton3: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(142),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enablefilledbutton4: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(108),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  enablefilledbutton5: {
    backgroundColor: Global.color.black,
   width: normalizeWidth(300),
    height: normalizeHeight(58),
   // marginHorizontal:normalizeWidth(2),
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  enablefilledbutton6: {
    backgroundColor: Global.color.primary,
   width: normalizeWidth(300),
    height: normalizeHeight(48),
   // marginHorizontal:normalizeWidth(2),
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  // enablefilledbutton6: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(213),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  // enablefilledbutton6: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(375),
  //   height: normalizeHeight(50),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  // enablefilledbutton8: {
  //   backgroundColor: Global.color.cyanblue,
  //   width: normalizeWidth(107),
  //   height: normalizeHeight(33),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  // disablefilledbutton1: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(250),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton2: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(150),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton3: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(142),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton4: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(108),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton5: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(343),
  //   height: normalizeHeight(50),
  //   borderRadius: 10,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton6: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(213),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton6: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(375),
  //   height: normalizeHeight(50),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disablefilledbutton8: {
  //   backgroundColor: Global.color.disablecyan,
  //   width: normalizeWidth(107),
  //   height: normalizeHeight(33),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  // enableoutlinebutton1: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(250),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enableoutlinebutton2: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(150),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enableoutlinebutton3: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(142),
  //   height: normalizeHeight(48),
  //   borderRadius: 12,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enableoutlinebutton4: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(108),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enableoutlinebutton5: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(343),
  //   height: normalizeHeight(50),
  //   borderRadius: 10,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // enableoutlinebutton6: {
  //   borderRadius: Global.color.cyanblue,
  //   borderWidth: 1,
  //   width: normalizeWidth(213),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  enableoutlinebutton7: {
    borderRadius: Global.color.cyanblue,
    borderWidth: 1,
    width: normalizeWidth(375),
    height: normalizeHeight(50),
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },

  enableoutlinebutton8: {
    borderRadius: Global.color.cyanblue,
    borderWidth: 1,
    width: normalizeWidth(107),
    height: normalizeHeight(33),
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },

  disableoutlinebutton1: {
    borderRadius: Global.color.disablecyan,
    borderWidth: 1,
    width: normalizeWidth(250),
    height: normalizeHeight(48),
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  disableoutlinebutton2: {
    borderRadius: Global.color.disablecyan,
    borderWidth: 1,
    width: normalizeWidth(150),
    height: normalizeHeight(38),
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  disableoutlinebutton3: {
    borderRadius: Global.color.disablecyan,
    borderWidth: 1,
    width: normalizeWidth(142),
    height: normalizeHeight(48),
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  disableoutlinebutton4: {
    borderRadius: Global.color.disablecyan,
    borderWidth: 1,
    width: normalizeWidth(108),
    height: normalizeHeight(38),
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  disableoutlinebutton5: {
    borderRadius: Global.color.disablecyan,
    borderWidth: 1,
    width: normalizeWidth(343),
    height: normalizeHeight(50),
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  // disableoutlinebutton6: {
  //   borderRadius: Global.color.disablecyan,
  //   borderWidth: 1,
  //   width: normalizeWidth(213),
  //   height: normalizeHeight(38),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },
  // disableoutlinebutton7: {
  //   borderRadius: Global.color.disablecyan,
  //   borderWidth: 1,
  //   width: normalizeWidth(375),
  //   height: normalizeHeight(50),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  // disableoutlinebutton8: {
  //   borderRadius: Global.color.disablecyan,
  //   borderWidth: 1,
  //   width: normalizeWidth(107),
  //   height: normalizeHeight(33),
  //   borderRadius: 8,
  //   alignItems: 'center',
  //   justifyContent: 'center',
  //   alignSelf: 'center',
  // },

  container: {
    width: '100%',
    height: '100%',
    flex: 1,
  },
  innercontainer: {
    paddingHorizontal: normalizeWidth(15),
  },

  bgcontainer: {
    width: '100%',
    height: '100%',
    flex: 1,
    backgroundColor: Global.color.primary,
  },

  // JustSBFDrow: {
  //   justifyContent: 'space-between',
  //   flexDirection: 'row',
  // },
  JustCFlexDRAlignItemC: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  JustAlignCenter: {
    justifyContent: 'center',
    alignItems: 'center',
  },

  expandFonttext: {
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fb,
    color: Global.color.white25070,
    letterSpacing: 0.3,
    fontWeight: '500',
  },
  bxName: {
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fb,
    color: Global.color.white25070,
    letterSpacing: 0.3,
    fontWeight: '500',
    marginLeft: normalizeWidth(10),
  },
  bxMainview: {
    marginHorizontal: normalizeWidth(15),
    marginBottom: normalizeHeight(10),
    paddingLeft: normalizeWidth(15),
    paddingRight: normalizeWidth(14),
    backgroundColor: Global.color.navyblueColor,
    borderRadius: 10,
    paddingVertical: normalizeHeight(10),
  },
  bxcurrentValue: {
    fontSize: heightPercentageToDP('2.23%'),
    lineHeight: heightPercentageToDP('2.89%'),
    fontFamily: Global.font.font_family_fb,
    color: Global.color.white25090,
    letterSpacing: 0.3,
    fontWeight: '500',
  },
  bxinvestedValue: {
    fontSize: normalizeHeight(13),
    lineHeight: normalizeHeight(18),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
    fontWeight: '400',
    color: Global.color.white50,
  },
  investedamount: {
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fb,
    letterSpacing: 0.3,
    fontWeight: '500',
    color: Global.color.white25070,
    marginTop: normalizeHeight(3),
  },
  bxGrowthtext: {
    fontSize: heightPercentageToDP('1.71%'),
    lineHeight: heightPercentageToDP('2.37%'),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
    fontWeight: '400',
    color: Global.color.white50,
  },
  bxGrowthtextamt: {
    fontSize: normalizeHeight(15),
    fontFamily: Global.font.font_family_fb,
    letterSpacing: 0.3,
    fontWeight: '500',
    marginTop: normalizeHeight(3),
  },
  subContainer: {
    paddingTop: normalizeHeight(5),
  },
  bottomText: {
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
    fontWeight: '400',
    color: Global.color.white25090,
  },
  bottomSubText: {
    fontSize: normalizeHeight(19),
    lineHeight: normalizeHeight(24),
    fontFamily: Global.font.font_family_fb,
    letterSpacing: 0.3,
    fontWeight: '500',
    color: Global.color.cyanblue,
    marginTop: normalizeHeight(4),
  },
  bottomContainer: {
    height: normalizeHeight(90),
    backgroundColor: Global.color.navyblueColor,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingLeft: normalizeWidth(17),
    paddingRight: normalizeWidth(15),
    position: 'absolute',
    bottom: 0,
    width: '100%',
    justifyContent: 'center',
  },
  rowView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headingText1: {
    fontSize: normalizeHeight(19),
    lineHeight: normalizeHeight(24),
    fontFamily: Global.font.font_family_fb,
    letterSpacing: 0.3,
    fontWeight: '500',
    color: Global.color.lightgrey,
  },
  headingText2: {
    fontSize: normalizeHeight(15),
    lineHeight: normalizeHeight(20),
    fontFamily: Global.font.font_family_fr,
    letterSpacing: 0.3,
    fontWeight: '400',
    color: Global.color.white25070,
    marginTop: normalizeHeight(10),
  },
  submitbtn: {
    position: 'absolute',
    bottom: normalizeHeight(50),
    left: 0,
    zIndex: 1,
    justifyContent: 'center',
    marginHorizontal: normalizeWidth(16)
  },
  noTrans: {
    color: Global.color.white,
    fontSize: normalizeHeight(20),
    textAlign: 'center',
    letterSpacing: 1,
    marginTop: '65%',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: Global.font.font_family_fr,
  }

});

export default GlobalStyles;
