import { Dimensions } from 'react-native';
import { SERVERURL, DIFENZ_BASE_URL } from '../config';
const windowsHeight = Dimensions.get('window').height;
const windowsWidth = Dimensions.get('window').width;
const headerheight = windowsWidth > 400 ? 109 : 42;
const footerheight = 74;

const ENV_KEYS = {
  DEV: {
    TYPE: 1,
    API_HOST: 'https://uat-api.augmontgold.com/',
    IS_LIVE: false,
  },
  QA: {
    TYPE: 2,
    API_HOST: 'https://uat-api.augmontgold.com/',
    IS_LIVE: false,
  },
  UAT: {
    TYPE: 3,
    API_HOST: 'https://uat-api.augmontgold.com/',
    IS_LIVE: false,
  },
  LIVE: {
    TYPE: 4,
    API_HOST: 'https://uat-api.augmontgold.com/',
    IS_LIVE: true,
  },
};

const ENV = ENV_KEYS.DEV;

export default {
  color: {
    verydarkblue: '#ff7ad5',
    lightpink:'#e941ac',  //fe93dc
    smokeygray: '#707070',
    orange2: '#FF8800',
    black2c:'#231F20',
    primary:'#ffffff',
    primaryrgb: 'rgba(14,38,118,255)',
    blue: '#0F99FA',
    darkgreyclr:'#71727a',
    error: '#FF0000',
    navyblueColor: '#151D29',
    skydarkColor: '#3EFFE8',
    darkBlue1Color: '#12263E',
    lightGreen1Color: '#2AF598',
    magentaColor: '#9A61F3',
    darkyellow:'#FF8C21',
    darkGrey: '#515c6f',
    whiteFive: '#e8e8e8',
    darkgrey45:'#696974',
    transparent: 'transparent',
    gray55:'#A3A4A6',
    clearBlack: 'rgba(0, 0, 0, 0.7)',
    clearLightBlack: 'rgba(0, 0, 0, 0.3)',
    clearLightBlack2: 'rgba(0, 0, 0, 0.2)',
    clearLightBlack1: 'rgba(0, 0, 0, 0.1)',
    clearLightBlack4: 'rgba(0, 0, 0, 0.4)',
    trackblue: '#C6E7FF',
    orange: '#FFC107',
    lightgrey66:'#DBDBDE',
    buttonblue: '#139AF9',
    darkBlueColor: '#24345A',
    bgrfaintblue: '#293A64',
    darkprimary: '#192440',
    textlabel: '#293A64',
    grey: '#F2F2F2',
    textColor:'#403390',
    white: '#FFFFFF',
    black: '#000000',
    blackorg: '#000000',
    lightgrey55:'#979797',
    black3color:'#171725',
    blackone:'#1A1C1E',
    light5grey:'#D8D8D8',
    darkorggrey:'#92929D',
    light2black:'#44444F',
    lightblackclr:'#898a91',
    blue4:'#2563eb',
    darkorange:'#f04444',
    lightgrey: '#FFFFFF',
    lightorgrey:'#DCE1EF',
    blackc:'#0D101C',
    strokeclr :'#EDF1F3',
    faintBlack: '#323232',
    drkgrey:'#6E7591',
    blacksaid:'#111827',
    borderColor: '#EBF0F3',
    boxcolor: '#c4c4c4',
    lightgraydark:'#767E8C',
    dalGreyColor:'#333A42',
    placeholder: '#989898',
    blackcc:'#3A3F47',
    inputtextcolor: '#555555',
    googleblue: '#4A7AFF',
    textbackground: '#ECECEC',
    calendergrey: '#A0A0A0',
    grey44:'#B9B9B9',
    grey30:'#E5E5E5',
    skycolorbk:'#F5F5F5',
    yellow: '#FBB03B',
    greyborder22:'#E0E5ED',
    lightgrey22:'#4F4F4F',
    lightgreyblue:'#606A7B',
    darklightGrey32:'#212121',
    gradientgreen: '#1F3F4E',
    greyblacklight:'#A9B0C5',
    blue3:'#7461EA',
    lightblue3:'#dbd6fd',
    lightgreen: '#21D363',
    purple: '#381F4E',
    darkgrey: '#414141',
    boldgrey: '#1C2C3C',
    grey2: '#8992A7',
    red: '#EE5166',
    lightgreen:'#24A19C',
    lightyellow: '#FFEDD0',
    hallowgreen: '#B9FFD3',
    light22grey:'#EAE9F0',
    whiteopacity: 'rgba(255, 255, 255, 0.5)',
    primaryborder: 'rgba(36, 52, 90, 0.25)',
    faintBlackrgb: 'rgba(50, 50, 50, 0.75)',
    gradientblue: '#00FFF0',
    oppwhite: '#FBFBFB',
    blackCC:'#4A4A4A',
    growthGreen: '#7EDB7C',
    graphgreen: '#1EB27A',
    goldColor: '#FFC54B',
    goldprice: '#FFE180',
    goldlightColor: '#FFE8A7',
    silverColor: '#D4E3E8',
    orangeColor: '#ED752E',
    darkLightGrey: '#dbdbdb',
    darkThemeColor: '#455A8A',
    veryLightGrey: '#efefef',
    lightSilverColor: '#EEF2FF',
    bluelight:'#1685FC',
    lightCoffeeColor: '#EFF0EA',
    lightGreen: '#28C325',
    blackz:'#282828',
    lightGreenColor: '#D9FFF9',
    lightGreenYellowColor: '#E9FAE8',
    lightYellowColor: '#F9FFE7',
    themeColor: '#0B1D33',
    lightThemeColor: '#949CB1',
    lightGrey3Color: '#666666',
    dune: '#384652',
    loaderColor: 'rgba(0, 0, 0, 0.1)',
    clearBlue: '#219eff',
    lightBlack2: '#444444',
    verylightGrey2: '#F7F7F7',
    verylightGrey3: '#F7F5FF',
    darkBlue: '#4042E2',
    toasterrorcolor: '#A94442',
    toasterrorbg: '#F2DEDE',
    toasterrorbr: '#EBCCD1',
    toastsuccesscolor: '#3C763D',
    toastsuccessbg: '#DFF0D8',
    toastsuccessbr: '#D6E9C6',
    lightGrey: '#7d8aa0',
    greyishBrown: '#404040',
    warmGrey: '#868686',
    purpleGrey: '#8c8a8c',
    paleGrey55: '#efeef2',
    skyColor: '#38ecff',
    lightYellow1Color: '#FFFBEB',
    darkPink: '#DD636E',
    lightGrey2: '#dfdfdf',
    ebonyClay: '#242A34',
    cyanblue: '#41AEFB', // For btn
    disablecyan: '#4B6B86', // For disable btn
    zeusgreen: '#1E1E1E',
    mirage: '#151D29',
    blackperl: '#0C151F',
    cinder: '#030D17',
    ebony: '#0C121A',
    white10: 'rgba(250, 250, 250, 0.1)', // FAFAFA 10%
    newWhite10: 'rgba(255, 255, 255, 0.1)',
    newWhite70: 'rgba(255, 255, 255, 0.7)',
    white25: 'rgba(250, 250, 250, 0.25)',
    white50: 'rgba(250, 250, 250, 0.5)',
    white70: 'rgba(250, 250, 250, 0.7)',
    white75: 'rgba(255, 255, 255, 0.75)',
    white80: 'rgba(255, 255, 255, 0.8)',
    white25080: 'rgba(250, 250, 250, 0.8)',
    white25070: 'rgba(250, 250, 250, 0.7)',
    white25090: 'rgba(250, 250, 250, 0.9)',
    white20: 'rgba(250, 250, 250, 0.2)',
    borderUnselectedColor: 'rgba(187, 194, 204, 0.7)',
    green: '#14C265',
    silverBackground: '#BBC2CC',
    gold70: 'rgba(255, 232, 167, 0.7)',
    silver70: 'rgba(187, 194, 204, 0.7)',
    green80: 'rgba(20, 194, 101, 0.8)',
    green60: 'rgba(20, 194, 101, 0.6)',
    red80: 'rgba(218, 34, 34, 0.8)',
    cyanblue80: 'rgba(65, 174, 251, 0.8)',
    lightBlue: '#151D29',
    inActiveGoldSilver: 'rgba(250, 250, 250, 0.7)',
    lightGold: '#A47200',
    pinkColor: '#e941ac',
    lightpurpal: '#A0616A',
    lightsky: '#368AB0',
    lightBluestick: '#735BF6',
    lightGreen2Color60: 'rgba(20, 194, 101, 0.6)',
    errorRed: '#ED3A3A',
    lightBlack3: '#15243B',
    blue2: '#0F1621',
    primarycolor: '#0C121A',
    statusbarColor: 'rgba(11, 29, 50, 1)',
    //TextWhiteColor: 'rgba(250, 250, 250, 1)',
    TextLightBlue: '#43A2FF',
    roundBg: '#8898AA',
    TextGray: 'rgba(250, 250, 250, 0.7)',
    // Boxcolor: '#15243B',
    lightyellow1: '#FCEED4',
    darkOrange: '#CF8800',
    lightGreen4: '#5AC97F',
    //primarycolor: 'rgba(11, 29, 50, 1)',
    // statusbarColor: 'rgba(11, 29, 50, 1)',
    TextWhiteColor: "rgba(250, 250, 250, 0.7)",
    TextWhiteColor5: "rgba(250, 250, 250, 0.5)",
    TextWhiteColorbk: 'rgba(250, 250, 250, 1)',
    //TextLightBlue:"rgba(65, 174, 251, 1)",
    //roundBg:"#8898AA",
    inactiveBtn: "#061D33",
    silver2: '#8BB9CC',
    gold2: '#B79F40',
    blueLight3: '#4B86B3',
    greenProgress: 'rgba(90, 201, 127, 0.9)',
    slateGrey: '#6E7985',
    orgGrey: '#6C7278',
    backdrop: 'rgba(0, 0, 0, 0.8)',
    border: '#535D69',
    successgreen: '#33B469',
    nileDarkGrey: '#243A58',
    gunsmokegray: '#838383',
    Dark: '#18202E',
    periwinklegrey: '#BCCFE7',
    Dark90: "rgba(31, 39, 52, 0.9)",
    vistaWhite: '#FAFAFA',
    darkFireFly: '#151D29',
    borderColor2:'#E2E2EA',
    dune: '#333333',
    paleSky: 'rgba(110, 121, 133, 0.9)',
    bleachedClay: 'rgba(36, 42, 52, 0.2)',
    pieBoder: 'rgba(33, 40, 52, 1)',
    cream: '#FCD8BD',
    backdrop: 'rgba(0, 0, 0, 0.5)',
    nebula: '#D1D3D4',
    jadeGreen: '#33B469',
    dustyGrey: '#999999',
    brightGrey: '#414B5E',
    crystalBlue: '#43A2FF',
    steelGray: '#6E7985',
    white25575: 'rgba(255, 255, 255, 0.7)',
    duskBlue: '#246287',
    ghostWhite: '#F3F9FF',
    peacockBlue: '#00598E',
    bleachedDark: '#1F2939',
    plantation: '#2B4C4E',
    taelBlue: '#1460AA',
    dodgerBlue: '#2F80ED',
    lightSlateGray: 'rgba(110, 121, 133, 0.3)',
    desaturatedBlue: '#1F2939',
    moderateBlue: '#517A9A',
    bleachedDark: '#1F2939',
    gunPowder: '#3C4E60',
  },
  font: {
    /*
     * Font_family_gm: 'Lato-Medium',
     * font_family_gr: 'Roboto-Regular',
     * font_family_gb: 'Roboto-Bold',
     * font_family_lo: 'Lato',
     */
    // Montserrat_Bold: 'Poppins-Bold',
    // Montserrat_BoldItalic: 'Poppins-BoldItalic',
    // Montserrat_ExtraBold: 'Poppins-ExtraBold',
    // Montserrat_ExtraLight: 'Montserrat-ExtraLight',
    // Montserrat_ExtraLightItalic: 'Montserrat-ExtraLightItalic',
    // Montserrat_Italic: 'Montserrat-Italic',
    // Montserrat_Light: 'Poppins-Light',
    // Montserrat_Medium: 'Poppins-Medium',
    // Montserrat_MediumItalic: 'Poppins-MediumItalic',
    // Montserrat_Regular: 'Poppins-Regular',   //RUN
    // Montserrat_SemiBold: 'Poppins-SemiBold',
    // Montserrat_SemiBoldItalic: 'Poppins-SemiBoldItalic',

    font_family_fl: 'Poppins-Light',
    font_family_fr: 'Poppins-Regular',
    font_family_fb: 'Poppins-Bold',
    TextRegular: "Poppins-Regular",
    TextBold: "Poppins-Bold",
    TextMedium: "Poppins-Medium",
    bold: "Poppins-Bold",
    extraBold: 'Poppins-ExtraBold',
    light: 'Poppins-Light',
    regular: "Poppins-Regular",
    semiBold: 'Poppins-SemiBold'

  },
  structure: {
    headerHeight: headerheight,
    footerHeight: footerheight,
    bodyHeightWithoutH: windowsHeight - headerheight,
    bodyHeightWithoutF: windowsHeight - footerheight,
    bodyHeightWithoutHF: windowsHeight - (headerheight + footerheight),
    screenHeight: windowsHeight,
    screenWidth: windowsWidth,
  },

  SCREENS: {
    DASHBOARD: 'Dashboard',
    GOLD_DASHBOARD: 'GoldDashboard',
    HOME: 'Home',
    GOLDLOCKER: 'GoldLocker',
    SELL: 'Sell',
    SELLACCOUNT: 'SellAccount',
    TRANSACTIONSTATUS: 'TransactionStatus',
    GIFT: 'Gift',
    MYCONTACT: 'MyContact',
    OTP: 'Otp',
    GIFTTRANSACTIONSTATUS: 'GiftTransactionStatus',
    BUY: 'Buy',
    NEWINVESTORINFO: 'NewInvestorinfo',
    TRANSACTIONSTATUSBUY: 'TransactionStatusBuy',
    DELIVERYPRODUCT: 'DeliveryProduct',
    PRODUCTDETAILS: 'ProductDetails',
    ORDERSUMMARY: 'OrderSummary',
    SHIPPINGADDRESS: 'ShippingAddress',
    DELIVERYTRANSACTIONSTATUS: 'DeliveryTransactionStatus',
    PASSBOOK: 'Passbook',
    HISTORY: 'History',
    SELLPAYOUTDETAILS: 'SellPayoutDetails',
    GIFTHISTORY: 'GiftHistory',
    BUYINVOICE: 'BuyInvoice',
    DELIVERYHISTORY: 'DeliveryHistory',
    DELIVERYINVOICE: 'DeliveryInvoice',
    WELCOME: 'Welcome',
    FDDASHBOARD: 'FdDashboard',
    NEWFIXEDDEPOSIT: 'NewFixedDeposit',
    DEPOSITSCHEMES: 'DepositSchemes',
    FDBANKACCOUNT: 'FdBankAccount',
    FDNOMINEE: 'FdNominee',
    ASSIGNNOMINEE: 'AssignNominee',
    UPLOADPANCARDVERIFICAITON: 'UploadPanCardVerification',
    PANCARDVERIFICATION: 'PanCardVerification',
    EDITEXPENSE: 'EditExpense'
  },
  URL: {
    DIRECTIONS_MAP_API:
      'https://www.google.com/maps/dir/?api=1&travelmode=driving&dir_action=navigate&destination=',
    LOGIN_API: `${ENV.API_HOST}api/merchant/v1/auth/login`,
    PRODUCT_LIST: `${ENV.API_HOST}api/merchant/v1/products`,
    GOLD_SILVER_RATES: `${ENV.API_HOST}api/merchant/v1/rates`,
    ADD_NEW_USER: `${ENV.API_HOST}api/merchant/v1/users`,
    ADD_NEW_BANK: `${ENV.API_HOST}api/merchant/v1/users/Yuyu02412/banks`,
    LIST_BANKS: `${ENV.API_HOST}api/merchant/v1/users/Yuyu02412/banks`,
    DEL_BANK_API: `${ENV.API_HOST}api/merchant/v1/users/Yuyu02412/banks`,
    PASSBOOK_API: `${ENV.API_HOST}api/merchant/v1/users/Yuyu02412/passbook`,
    SELL_GOLD_SILVER: `${ENV.API_HOST}api/merchant/v1/sell`,
    TRANSFER_GOLD_SILVER: `${ENV.API_HOST}api/merchant/v1/transfer`,
    GET_STATES_API: `${ENV.API_HOST}api/merchant/v1/master/states`,
    GET_CITIES_API: `${ENV.API_HOST}api/merchant/v1/master/cities`,
    BUY_GOLD_SILVER: `${ENV.API_HOST}api/merchant/v1/buy`,
    // User api
    GET_BALANCE: `${SERVERURL}goldsilver/passbook/getbalance`,
    CHECK_INVESTOR_GOLDSILVER: `${SERVERURL}goldsilver/investor/check`,
    INSERT_BANK_DETAILS: `${SERVERURL}goldsilver/bank`,
    USER_SELL_GOLD_SILVER: `${SERVERURL}goldsilver/sell`,
    USER_BUY_GOLD_SILVER: `${SERVERURL}goldsilver/purchase`,
    USER_GET_BANK_LIST: `${SERVERURL}goldsilver/bank`,
    DIFENZ_BASE_URL: `${DIFENZ_BASE_URL}api/verify/verifyBank`,
    USER_GIFT: `${SERVERURL}goldsilver/gift`,
    USER_GIFT_RECIPENT: `${SERVERURL}goldsilver/gift/recipent`,
    PASSBOOK_LIST: `${SERVERURL}goldsilver/passbook`,
    RESEND_OTP: `${SERVERURL}goldsilver/gift/resendotp`,
    VERIFY_OTP: `${SERVERURL}goldsilver/gift/verifyotp`,
    BOUGHT_SELL_DETAILS: `${SERVERURL}goldsilver/passbook/boughtselldetails`,
    PAYOUT_DETAILS: `${SERVERURL}goldsilver/passbook/payoutdetails`,
    GIFT_DETAILS: `${SERVERURL}goldsilver/passbook/giftdetails`,
    WITHDRAW_GIFT: `${SERVERURL}goldsilver/passbook/withdrawgift`,
    PASSBOOK_INVOICE_API: `${SERVERURL}goldsilver/passbook/invoice`,
    BANK_LIST: `${SERVERURL}master/banklist`,
    DELIVERY_DETAILS: `${SERVERURL}goldsilver/passbook/deliverydetails`,
    DELIVERY_DETAILS_INVOICE: `${SERVERURL}goldsilver/passbook/deliverydetailsinvoice`,
    BANK_ACCOUNT_EXISTS: `${SERVERURL}mutualfund/account/exists`,
    PAYMENT_COMPLETION: `${SERVERURL}goldsilver/paymentcompletion`,
  },
  KEYS: {
    GOOGLE_MAPS: 'AIzaSyBCMJ-LYHH4Uv5l_mkkRsyR5j8SqkXqgwk',
    EMAIL_ID: 'sumit@rewardwale.in',
    PASSWORD: 'LaF@sJgv23!$f#',
    USER_UNIQUE_ID: 'Yuyu02412',
    USER_MOBILE_NO: '9729799040',
    DIFENZ_KEY:
      'ZnVuY3Rpb24gbm93KCkgeyBbbmF0aXZlIGNvZGVdIH1WYWx1ZUZsb2F0IFRlY2hub2xvZ2llcw==',
    AUTHORIZATION:
      'ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmZhV1FpT2pJekxDSnRiMkpwYkdVaU9pSTVPRGd3TlRRd01UQTVJaXdpWVdOamIzVnVkSFI1Y0dVaU9pSlFaWEp6YjI1aGJDSXNJbWxoZENJNk1UWXlOakUxTmpjNE5Td2laWGh3SWpveE5qVTNOamt5TnpnMWZRLmZEd1RhQmp3U05vREtfSERjLXdXQmtrWTVsSjhiMUtndjlJSklvTWNrNTkxakZrdTJRWjhsZWtKeFhDSU9vX1BVWGdHOUV4NzVCQVdGZ083dERTeTRiMkk0NmNFWWRHdDctMTZ4S055ZEk2U2g0dldWVUxKUW9ST1AtaWJDQ0xiWlJHN204ZDZkalp5S3hPRERMUGNyTlBMakFxVHA4OHMwZTJzZlJxa1hzc1dwcERxUHdaeW0wMVU0dEhNbGFpWWtabE9uZ3pHejQyRWlnOGdnZXd0ZHhWMDIxSFNWNk14dnhJU1JOS2ltZU53UlQ0dWlkQjVCVkNKbmUwbDJtMk4tNDgxV2YtS19ZVlR6M3BDNUxZQV84dDlOOGxxY2R6b2VtUk9oWXhpNTRVRVY2WGxaNl9MNXFjMDlscVJKY0Y5dDFnVTNxMXdqNmFtTGQ4eVVBRnE4aURyeGx1MURKTWY2VE93QVVUa0xvV3dUT3RFa2ZseXdENDdMWVpYV2lYQVJLQjYzakFjdW96eWFoR2Zwd01IN0hrUlVkSkU3emVkRF85SHZMeEwybm5OU2tBMUFEVDBkcnFwZU02eTA2Wmlwa2gwdkpKWkNxM3h6aW9xYS1IYVhoOGgyMTBLeThtbVZwOEZwVERYTjcydjBudlRUeHpUODIyTnhDeXZTRjVScllJQnJaaVpOUkZyMzFsR0dlLVRoeERITkZnMzVGdDBkUTMwakQtdTl1TGhmMWdkUk95bHpCNFVTRnZXYkFSSTkyTG5vVVE5TG90d2pHUkJZbUJOM3lwTVhES3JrZ0lDV2x3Q2xHZmJfajItbGVRNVlqeHNrQ1BTd3hfUkVuRzMtVU4waHhMVkoxdHpWLVh2Uk1MTW1ZNE8zZU14eC03aXV5LU1QVlBkMVA0',
  },
  ASYNC_KEYS: {
    LANGUAGE: '@language',
    ACCESS_TOKEN: '@userToken',
    LAUNCHED: '@launched',
    GUEST_USER_FIRSTNAME: '@guestUserFirstname',
    GUEST_USER_LASTNAME: '@guestUserLastname',
    USER_DETAILS: '@userDetails',
    USER_SET_LOCATION: '@userSetLocation',
    RANDOM_NUMBER: '@randomNumber',
    COUNTDOWN: '@countDown',
    RAZORPAY_PAYMENT_ID: '@razorpay_payment_id',
    INTRO_SLIDER: '@introslider',
  },
  Regex: {
    name: /^[\p{Arabic}a-zA-Z ]+\h?[\p{Arabic}a-zA-Z ]*$/,
    nameNumber: /^[\p{Arabic}a-zA-Z0-9 ]+\h?[\p{Arabic}a-zA-Z0-9 ]*$/,
    otp: /^\d{6}$/,
    reg: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    number: /^(\+\d{1,3}[- ]?)?\d{10}$/,
    checkNumber: /^[0-9.]+$/,
    checkMobileNumber: /^[0-9]+$/,
    checkMobileNoFirstLetter: /^[6-9]{1}[0-9]+$/,
    regex: /^[1-9]{1}[0-9]{2}[0-9]{3}$/,
    decimalNumber: /[^0-9\.]/g,
    decimalFourDigit: /^\d[0-9]+\.\d\d\d\d$/g,
    decNum: /^\d{0,9}(\.\d{1,4})?$/
  },

};
